.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1995 Michael Chastain (mec@shell.portal.com), 15 April 1995.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Fri Jan 31 16:11:17 1997 by Eric S. Raymond <esr@thyrsus.com>
.\" Modified Wed Jul 30 14:25:16 1997 by Paul Slootman <paul@wurtel.demon.nl>
.\" Translation (c) 1998 Przemek Borys <pborys@dione.ids.pl>
.\" Sync with man-pages 1.47 A. Krzysztofowicz <ankry@mif.pg.gda.pl>
.\"
.TH ADJTIMEX 2 1997-07-30 "Linux 2.0" "Podrêcznik programisty Linuksa"
.SH NAZWA
adjtimex \- dopasowanie zegara w j±drze
.SH SK£ADNIA
.B #include <sys/timex.h>
.sp
.BI "int adjtimex(struct timex *" "buf" );
.SH OPIS
Linux u¿ywa algorytmu dopasowywania Davida L. Millsa (zobacz w RFC 1305).
Wywo³anie systemowe
.B adjtimex
czyta i opcjonalnie ustawia parametry steruj±ce tego algorytmu.
.B adjtimex
pobiera wska¼nik do struktury
.IR timex ,
poprawia parametry w j±drze na podstawie warto¶ci przekazanych w polach
i zwraca tê sam± strukturê z bie¿±cymi ustawieniami j±dra.
Struktura jest zadeklarowana nastêpuj±co:
.PP
.RS
.nf
struct timex {
    int modes;           /* prze³±cznik trybu */
    long offset;         /* offset czasu (usec) */
    long frequency;      /* offset czêstotliwo¶ci (skalowany ppm) */
    long maxerror;       /* maksymalny b³±d (usec) */
    long esterror;       /* obliczony b³±d (usec) */
    int status;          /* komenda/status zegara */
    long constant;       /* sta³a czasu pll */
    long precision;      /* dok³adno¶æ zegara (usec) (tylko do odczytu) */
    long tolerance;      /* tolerancja czêstotliwo¶ci zegara (ppm)
                            (tylko do odczytu) */
    struct timeval time; /* aktualny czas (tylko do odczytu) */
    long tick;           /* czas miedzy tykniêciami zegara (usec) */
};
.fi
.RE
.PP
Pole
.I modes
okre¶la, które parametry (je¶li w ogóle) ustawiæ.
Mo¿e ono zawieraæ
.RI bitowe or
kombinacji zera lub wiêcej spo¶ród nastêpuj±cych bitów:
.PP
.RS
.nf
#define ADJ_OFFSET            0x0001 /* offset czasu */
#define ADJ_FREQUENCY         0x0002 /* offset czêstotliwo¶ci */
#define ADJ_MAXERROR          0x0004 /* maksymalny b³±d czasu */
#define ADJ_ESTERROR          0x0008 /* obliczany b³±d czasu */
#define ADJ_STATUS            0x0010 /* status zegara */
#define ADJ_TIMECONST         0x0020 /* sta³a czasu pll */
#define ADJ_TICK              0x4000 /* warto¶æ tykniêcia */
#define ADJ_OFFSET_SINGLESHOT 0x8001 /* staromodne adjtime */
.fi
.RE
.PP
Zwyczajni u¿ytkownicy s± ograniczeni do warto¶ci zero dla
.IR mode .
Jedynie superu¿ytkownik mo¿e ustawiaæ jakiekolwiek parametry.
.br
.ne 12v
.SH "WARTO¦Æ ZWRACANA"
Po pomy¶lnym zakoñczeniu,
.B adjtimex
zwraca stan zegara z
.PP
.RS
.nf
#define TIME_OK   0 /* zegar zsynchronizowany */
#define TIME_INS  1 /* dodaj sekundê przestêpn± */
#define TIME_DEL  2 /* skasuj sekundê przestêpn± */
#define TIME_OOP  3 /* sekunda przestêpna trwa */
#define TIME_WAIT 4 /* wyst±pi³a sekunda przestêpna */
#define TIME_BAD  5 /* zegar nie zsynchronizowany */
.fi
.RE
.PP
W przypadku b³êdu,
.B adjtimex
zwraca \-1 i ustawia
.IR errno .
.SH B£ÊDY
.TP
.B EFAULT
.I buf
nie wskazuje do zapisywalnej pamiêci.
.TP
.B EPERM
.I buf.mode
jest niezerowe, a u¿ytkownik nie jest superu¿ytkownikiem.
.TP
.B EINVAL
Próbowano ustawiæ
.I buf.offset
na warto¶æ poza obszarem od \-131071 do +131071,
lub ustawiæ
.I buf.status
na warto¶æ inn± ni¿ te wymienione powy¿ej, lub ustawiæ
.I buf.tick
na warto¶æ spoza zakresu
.RB 900000/ HZ
do 
.RB 1100000/ HZ ,
gdzie
.B HZ
jest czêstotliwo¶ci± przerwania systemowego timera.
.SH "ZGODNE Z"
\fBadjtimex\fP jest specyficzny dla Linuksa i nie powinien byæ u¿ywany w
programach, które maj± byæ przeno¶ne. W SVr4 istnieje podobna, lecz mniej
ogólna funkcja \fBadjtime\fR.
.SH "ZOBACZ TAK¯E"
.BR settimeofday (2).
