.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" {PTM/PB/0.1/09-05-1999/"wej¶cie/wyj¶cie portowe"}
.\" Last Update: Andrzej Krzysztofowicz <ankry@mif.pg.gda.pl>, Jan 2002,
.\"              manpages 1.47
.\"
.\" Copyright (c) 1995 Paul Gortmaker
.\" (gpg109@rsphy1.anu.edu.au)
.\" Wed Nov 29 10:58:54 EST 1995
.\" 
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\"
.TH OUTB 2 1995-11-29 "Linux" "Podrêcznik programisty Linuksa"
.SH NAZWA
outb, outw, outl, outsb, outsw, outsl \- zapis na port
.br
inb, inw, inl, insb, insw, insl \- odczyt z portu
.br
outb_p, outw_p, outl_p, inb_p, inw_p, inl_p \- opó¼niaj±ce operacje we/wy
.sp
.SH OPIS
Ta rodzina funkcji jest u¿ywana do wykonywania niskopoziomowych odczytów z
portu i zapisów na port.
S± one przeznaczone g³ównie do u¿ytku wewn±trz j±dra, lecz mog± byæ te¿
u¿ywane w warstwie u¿ytkownika.
.\" , przy podaniu nastêpuj±cych danych w dodatku
.\" do tego, co podano w
.\" .BR outb (9).
.sp
Nale¿y je kompilowaæ z \fB\-O\fP lub \fB\-O2\fP, lub z czym¶ podobnym. Funkcje
te s± zdefiniowane jako makra inline i nie bêd± podstawione bez w³±czonej
optymalizacji, powoduj±c niezdefiniowane referencje podczas konsolidacji.
.sp
Aby przekazæ j±dru, ¿e warstwa u¿ytkownika chce uzyskaæ dostêp do ¿±danych
portów, nale¿y u¿yæ
.IR ioperm (2)
lub
.IR iopl (2).
B³±d podczas wykonywanie tej operacji, spowoduje b³±d ochrony pamiêci.

.SH "ZGODNE Z"
\fBoutb\fP i przyjaciele s± zale¿ne od sprzêtu na którym dzia³aj±. Argumenty
.I port
i
.I value
s± w odwrotnej kolejno¶ci ni¿ w wiêkszo¶ci implementacji DOSowych.
.SH "ZOBACZ TAK¯E"
.BR ioperm (2),
.BR iopl (2)
