.\" Translation (c) 2000 PTM Przemek Borys <pborys@dione.ids.pl>
.\" Last update: A. Krzysztofowicz <ankry@mif.pg.gda.pl>, Jan 2002,
.\"              manpages 1.47
.\"
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)setregid.2	6.4 (Berkeley) 3/10/91
.\"
.\" Modified Sat Jul 24 09:08:49 1993 by Rik Faith <faith@cs.unc.edu>
.\" Portions extracted from linux/kernel/sys.c:
.\"             Copyright (C) 1991, 1992  Linus Torvalds
.\"             May be distributed under the GNU General Public License
.\" Changes: Fri Jul 29 10:56:01 BST 1994 by Wilf. <G.Wilford@ee.surrey.ac.uk>
.\"          Tue Aug  2 14:56:48 BST 1994 by Wilf due to change in kernel.
.\"
.TH SETREUID 2 1994-08-02 "Linux 1.1.38" "Podrêcznik programisty Linuksa"
.SH NAZWA
setreuid, seteuid \- ustawienie rzeczywistego i/lub efektywnego ID u¿ytkownika
lub grupy
.SH SK£ADNIA
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.sp
.BI "int setreuid(uid_t " ruid ", uid_t " euid );
.br
.BI "int setregid(gid_t " rgid ", gid_t " egid );
.SH OPIS
.B setreuid
ustawia rzeczywisty i efektywny identyfikator u¿ytkownika bie¿±cego procesu.
Nieuprzywilejowani u¿ytkownicy mog± ustawiæ rzeczywisty ID u¿ytkownika na
podstawie rzeczywistego lub efektywnego ID u¿ytkownika, lub efektywny ID
u¿ytkownika na podstawie rzeczywistego, efektywnego lub zachowanego ID
u¿ytkownika.

Podanie warto¶ci \-1 dla rzeczywistego lub efektywnego ID u¿ytkownika wymusza
na systemie pozostawienie tego ID niezmienionym.

Je¶li rzeczywisty lub efektywny ID u¿ytkownika jest ustawiany na warto¶æ ró¿n±
od poprzedniego rzeczywistego ID u¿ytkownika, to zachowanemu ID u¿ytkownika
zostanie nadana warto¶æ nowego efektywnego ID u¿ytkownika.

Zupe³nie analogicznie
.B setregid
ustawia rzeczywisty i efektywny identyfikator grupy bie¿±cego procesu,
a wszystko powy¿ej nadal obowi±zuje po zmianie s³owa "u¿ytkownik" na "grupa".

.SH "WARTO¦Æ ZWRACANA"
Po pomy¶lnym zakoñczeniu zwracane jest zero. Po b³êdzie zwracane jest \-1
i odpowiednio ustawiane
.IR errno .
.SH B£ÊDY
.TP
.B EPERM
Proces nie jest procesem superu¿ytkownika, a za¿±dano zmian innych ni¿ (i)
zamiana efektywnego ID u¿ytkownika (grupy) z rzeczywistym lub (ii) ustawienie
jednej z tych warto¶ci na podstawie drugiej, lub (iii) ustawienie efektywnego
ID u¿ytkownika (grupy) na podstawie warto¶ci zachowanego ID u¿ytkownika
(grupy).
.SH UWAGI
Ustawianie efektywnego ID u¿ytkownika (grupy) na podstawie zachowanego ID
jest mo¿liwe poczynaj±c od wersji Linuksa 1.1.37 (1.1.38).
.SH HISTORIA
Funkcja
.B setreuid
pojawi³a siê w BSD 4.2.
.SH "ZGODNE Z"
BSD 4.3 (funkcje
.B setreuid
i
.B setregid
pojawi³y siê pierwotnie w 4.2BSD).
.SH "ZOBACZ TAK¯E"
.BR getuid (2),
.BR getgid (2),
.BR setuid (2),
.BR setgid (2),
.BR seteuid (2),
.BR setresuid (2)
