.\" Hey Emacs! This file is -*- nroff -*- source.
.\" 
.\" {PTM/PB/0.1/18-05-1999/"pobierz czas w sekundach"}
.\" Last update: A. Krzysztofowicz <ankry@mif.pg.gda.pl>, Jan 2002,
.\"              manpages 1.47
.\"
.\" Copyright (c) 1992 Drew Eckhardt (drew@cs.colorado.edu), March 28, 1992
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified by Michael Haardt <michael@moria.de>
.\" Modified Sat Jul 24 14:13:40 1993 by Rik Faith <faith@cs.unc.edu>
.\" Additions by Joseph S. Myers <jsm28@cam.ac.uk>, 970909
.\"
.TH TIME 2 1997-09-09 "Linux 2.0.30" "Podrêcznik programisty Linuksa"
.SH NAZWA
time \- pobranie czasu w sekundach
.SH SK£ADNIA
.B #include <time.h>
.sp
.BI "time_t time(time_t *" t );
.SH OPIS
\fBtime\fP zwraca czas od 1 stycznia 1970r 00:00:00 GMT,
mierzony w sekundach.

Je¶li
.I t
nie jest równe NULL, to zwracana warto¶æ jest równie¿ zapisywana w pamiêci
wskazywanej przez
.IR t .
.SH "WARTO¦Æ ZWRACANA"
W przypadku pomy¶lnego zakoñczenia, zwracana jest warto¶æ liczbowa dla czasu
w sekundach od Epoki. W przypadku b³êdu, zwracane jest ((time_t)\-1)
i odpowiednio ustawiane \fIerrno\fP.
.SH B£ÊDY
.TP
.B EFAULT
.I t
wskazuje poza dostêpn± dla u¿ytkownika przestrzeñ adresow±.
.SH UWAGI
POSIX.1 definiuje
.I liczbê sekund od Epoki
jako warto¶æ, które ma byæ interpretowana jako liczba sekund pomiêdzy
zadanym czasem a Epok±, obliczona jako ró¿nica czasów UTC z wykorzystaniem
uproszczonego wzoru, w którym ignorowane s± sekundy przestêpne, a wszystkie
lata podzielne przez 4 s± przestêpne. Warto¶æ ta nie jest tym samym, co
rzeczywista liczba sekund pomiêdzy zadanym czasem a Epok±, gdy¿ istniej±
sekundy przestêpne oraz zegary nie musz± byæ synchronizowane z czasem
standardowym. Ma to na celu spójn± interpretacjê dla liczby sekund od Epoki;
dodatkowe uzasadnienie mo¿na znale¼æ w POSIX.1 Annex B 2.2.2.
.SH "ZGODNE Z"
SVr4, SVID, POSIX, X/OPEN, BSD 4.3
.br
W BSD 4.3 wywo³anie to jest przedawnione z uwagi na
.BR gettimeofday (2).
POSIX nie okre¶la ¿adnych sytuacji b³êdnych.
.SH "ZOBACZ TAK¯E"
.BR ctime (3),
.BR date (1),
.BR ftime (3),
.BR gettimeofday (2)
