.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain.
.\"
.\" Translation update: Robert Luberda <robert@debian.org> Nov 2004, manpages 1.70
.\" $Id: undocumented.2,v 1.2 2004/11/21 11:50:55 robert Exp $
.\"
.TH UNDOCUMENTED 2 2003-02-01 "Linux 2.4.20" "Podrêcznik programisty Linuksa"
.SH NAZWA
madvise1,
rt_sigaction,
rt_sigpending,
rt_sigprocmask,
rt_sigqueueinfo,
rt_sigreturn,
rt_sigsuspend,
rt_sigtimedwait,
ugetrlimit
\- nieudokumentowane funkcje systemowe
.SH STRESZCZENIE
Nieudokumentowane funkcje systemowe.
.SH OPIS
J±dro 2.4.20 zna 253 wywo³ania systemowe (syscalls) dla architektury i386.
Wymienione powy¿ej nie zosta³y jeszcze udokumentowane.
.SH "ZOBACZ TAK¯E"
.BR obsolete (2),
.BR syscalls (2),
.BR unimplemented (2)
