.\" 1999 PTM Przemek Borys
.\" Copyright (c) 1985, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)aliases.5	8.2 (Berkeley) 12/11/93
.\"
.Dd 11 Grudnia, 1993
.Dt ALIASES 5
.Os BSD 4
.Sh NAZWA
.Nm aliases
.Nd plik z aliasami dla sendmaila
.Sh SK£ADNIA
.Nm aliases
.Sh OPIS
Plik ten opisuje aliasy dla
.Tn ID
u¿ytkownika, u¿ywane przez
.Pa /usr/sbin/sendmail .
Plik ten znajduje siê w
.Pa /etc
i jest sformatowany jako seria linii postaci
.Bd -filled -offset indent
nazwa: nazwa_1, nazwa2, nazwa_3, . . .
.Ed
.Pp
.Em nazwa
jest aliasowan± nazw±, a
.Em nazwa_n
to alias tej nazwy.
Linie rozpoczynaj±ce siê od bia³ej spacji uznawane s± za linie kontynuacji.
Linie rozpoczynaj±ce siê od
.Ql #
s± komentarzami.
.Pp
Aliasowania zachodzi tylko dla nazw lokalnych.
Pêtle nie pojawiaj± siê, gdy¿ ¿adna wiadomo¶æ do nikogo nie bêdzie wysy³ana
wiêcej ni¿ raz.
.Pp
Po dokonaniu aliasowania, lokalni odbiorcy, którzy maj± w swoim katalogu
domowym plik
.Dq Pa .forward
przerzuc± automatycznie wiadomo¶ci do listy u¿ytkowników z tego pliku.
.Pp
Jest to plik danych surowych. Rzeczywiste dane aliasowe znajduj± siê w
formacie binarnym w pliku
.Pa /etc/aliases.db
Aby go utworzyæ, u¿yj
.Xr newaliases 1 .
Po ka¿dej zmianie pliku z aliasami nale¿y wywo³ywaæ
.Xr newaliases
aby zmiany zaczê³y dawaæ efekt.
.Sh ZOBACZ TAK¯E
.Xr newaliases 1 ,
.Xr dbopen 3 ,
.Xr dbm 3 ,
.Xr sendmail 8
.Rs
.%T "SENDMAIL Installation and Operation Guide"
.Re
.Rs
.%T "SENDMAIL An Internetwork Mail Router"
.Re
.Sh B£ÊDY
Je¶li skompilowa³e¶
.Xr sendmail
z wsparciem dla DBM, zamiast NEWDB, to mo¿esz napotkaæ na problemy z
.Xr dbm 3
ograniczaj±cym pojedynczy alias do oko³o 1000 bajtów danych. 
Mo¿esz uzyskaæ d³u¿sze aliasy przez ``³añcuch''; tj. tworzenie ostatniej
nazwy aliasu nazw± `dummy', która jest kontynuacj± aliasu.
.Sh HISTORIA
Plik
.Nm
pojawi³ siê w
.Bx 4.0 .
