.\" 2000 PTM Przemek Borys <pborys@dione.ids.pl>
.TH pnm 5 "27 wrze¶nia 1991"
.SH NAZWA
pnm - przeno¶ny format dowolnej bitmapy
.SH OPIS
Programy
.I pnm
pracuj± z przeno¶nymi bitmapami, mapami szaro¶ci, pixmapami, tworzonymi w
segmentach
.I pbm, pgm,
i
.IR ppm .
Nie ma konkretnego formatu, zwi±zanego z
.IR pnm .
.SH "ZOBACZ TAK¯E"
anytopnm(1), rasttopnm(1), tifftopnm(1), xwdtopnm(1),
pnmtops(1), pnmtorast(1), pnmtotiff(1), pnmtoxwd(1),
pnmarith(1), pnmcat(1), pnmconvol(1), pnmcrop(1), pnmcut(1),
pnmdepth(1), pnmenlarge(1), pnmfile(1), pnmflip(1), pnmgamma(1),
pnmindex(1), pnminvert(1), pnmmargin(1), pnmnoraw(1), pnmpaste(1),
pnmrotate(1), pnmscale(1), pnmshear(1), pnmsmooth(1), pnmtile(1),
ppm(5), pgm(5), pbm(5)
.SH AUTOR
Copyright (C) 1989, 1991 Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
