.\" 2000 PTM Przemek Borys <pborys@dione.ids.pl>
.TH pnm 5 "27 września 1991"
.SH NAZWA
pnm - przenośny format dowolnej bitmapy
.SH OPIS
\fI Uwaga! To tłumaczenie może być nieaktualne!\fP
.PP
Programy
.I pnm
pracują z przenośnymi bitmapami, mapami szarości, pixmapami, tworzonymi w
segmentach
.I pbm, pgm,
i
.IR ppm .
Nie ma konkretnego formatu, związanego z
.IR pnm .
.SH "ZOBACZ TAKŻE"
anytopnm(1), rasttopnm(1), tifftopnm(1), xwdtopnm(1),
pnmtops(1), pnmtorast(1), pnmtotiff(1), pnmtoxwd(1),
pnmarith(1), pnmcat(1), pnmconvol(1), pnmcrop(1), pnmcut(1),
pnmdepth(1), pnmenlarge(1), pnmfile(1), pnmflip(1), pnmgamma(1),
pnmindex(1), pnminvert(1), pnmmargin(1), pnmnoraw(1), pnmpaste(1),
pnmrotate(1), pnmscale(1), pnmshear(1), pnmsmooth(1), pnmtile(1),
ppm(5), pgm(5), pbm(5)
.SH AUTOR
Copyright (C) 1989, 1991 Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
.SH "INFORMACJE O TŁUMACZENIU"
Powyższe tłumaczenie pochodzi z nieistniejącego już Projektu Tłumaczenia Manuali i 
\fImoże nie być aktualne\fR. W razie zauważenia różnic między powyższym opisem
a rzeczywistym zachowaniem opisywanego programu lub funkcji, prosimy o zapoznanie 
się z oryginalną (angielską) wersją strony podręcznika za pomocą polecenia:
.IP
man \-\-locale=C 5 pnm
.PP
Prosimy o pomoc w aktualizacji stron man \- więcej informacji można znaleźć pod
adresem http://sourceforge.net/projects/manpages\-pl/.
