.\" {PTM/AB/0.1/11-12-1998/"__setfpucw - zmiana s³owa kontrolnego koprocesora w architekturze i386"}
.\" t³umaczenie Adam Byrtek (abyrtek@priv.onet.pl)
.\" Aktualizacja do man-pages-1.44 - A. Krzysztofowicz (ankry@mif.pg.gda.pl)
.\" ------------
.\" Written Sat Mar  8 10:35:08 MEZ 1997 by J. "MUFTI" Scheurich (mufti@csv.ica.uni-stuttgart.de)
.\" ------------
.TH __SETFPUCW 3 "1997-03-08" "Linux i386" "Podrêcznik programisty Linuksa"
.SH NAZWA
__setfpucw \- zmiana s³owa kontrolnego koprocesora w architekturze i386
(przestarza³e)
.SH SK£ADNIA
.B #include <i386/fpu_control.h>
.sp
.BI "void __setfpucw((unsigned short) " slowo_kontrolne );
.br
.SH OPIS
Funkcja
.B __setfpucw()
wpisuje
.I slowo_kontrolne
do rejestrów fpu (floating point unit - jednostki zmiennoprzecinkowej)
w architekturze i386. S³owo to by³o u¿ywane do zmiany dok³adno¶ci
zmiennoprzecinkowej, zaokr±glania oraz wyj±tków zmiennoprzecinkowych.
.SH PRZYK£AD

.B __setfpucw(0x1372)

ustawia s³owo koprocesora w architekturze i386 na
.br
    - rozszerzon± dok³adno¶æ
.br
    - zaokr±glanie do najbli¿szego
.br
    - wyj±tki podczas przepe³nienia, dzielenia przez zero oraz gdy
warto¶æ nie jest liczb±
.br 
.SH DOSTÊPNO¦Æ
W glibc 2.1 ta funkcja ju¿ nie istnieje. Dostêpne s± nowe funkcje zgodne z
ISO C99 o prototyoach w
.IR /usr/include/fenv.h ,
takie jak
.IR fegetround ,
.IR fesetround ,
s³u¿±ce do ustawiania trybów zaokr±glania koprocesora; takie jak
.IR fegetenv ,
.IR feholdexcept ,
.IR fesetenv ,
.IR feupdateenv
s³u¿±ce do ustawiania ¶rodowiska zmiennoprzecinkowego; takie jak
.IR feclearexcept ,
.IR fegetexceptflag ,
.IR feraiseexcept ,
.IR fesetexceptflag ,
.IR fetestexcept ,
s³u¿±ce do obs³ugi wyj±tków zmiennoprzecinkowych.
.PP
Je¶li mimo wszystko potrzebny jest bezpo¶redni dostêp do s³owa kontrolnego
FPU, mo¿na pos³u¿yæ siê zdefiniowanymi w
.I /usr/include/fpu_control.h
makrami _FPU_GETCW i _FPU_SETCW.
.SH "ZOBACZ TAK¯E"
.BR feclearexcept (3)
.br
.I /usr/include/i386/fpu_control.h
