.\" {PTM/AB/0.1/11-12-1998/"acosh - odwrotno¶æ hiperbolicznej funkcji cosinus"}
.\" t³umaczenie Adam Byrtek (abyrtek@priv.onet.pl)
.\" Aktualizacja do man-pages 1.67 - Robert Luberda <robert@debian.org>, pa¼dziernik 2004
.\" ------------
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified 1993-07-24 by Rik Faith (faith@cs.unc.edu)
.\" Modified 2002-07-25 by Walter Harms
.\" 	(walter.harms@informatik.uni-oldenburg.de)
.\"
.TH ACOSH 3 2002-07-25 "" "Podrêcznik programisty Linuksa"
.SH NAZWA
acosh, acoshf, acoshl \- funkcja odwrotna do cosinusa hiperbolicznego
.SH SK£ADNIA
.nf
.B #include <math.h>
.sp
.BI "double acosh(double " x );
.sp
.BI "float acoshf(float " x );
.sp 
.BI "long double acoshl(long double " x );
.fi
.SH OPIS
Funkcja \fBacosh()\fP oblicza warto¶æ funkcji odwrotnej do cosinusa
hiperbolicznego dla \fIx\fP, to znaczy warto¶æ, dla której cosinus
hiperboliczny wynosi \fIx\fP.
Je¶li \fIx\fP wynosi mniej ni¿ 1.0, \fBacosh()\fP zwraca warto¶æ nie bêd±c±
liczb± (NaN) i ustawia \fIerrno\fP.
.SH B£ÊDY
.TP
.B EDOM
\fIx\fP jest poza zakresem.
.SH "ZGODNE Z"
SVID 3, POSIX, BSD 4.3, ISO 9899.
Warianty float i long double s± wymagane przez C99
.SH "ZOBACZ TAK¯E"
.BR asinh (3),
.BR atanh (3),
.BR cosh (3),
.BR sinh (3),
.BR tanh (3)
