.\" {PTM/AB/0.1/13-12-1998/"htonl, htons, ntohl, ntohs - konwersja warto¶ci pomiêdzy lokalnym a sieciowym porz±dkiem bajtów"}
.\" t³umaczenie Adam Byrtek (abyrtek@priv.onet.pl)
.\" ------------
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 21:29:05 1993 by Rik Faith (faith@cs.unc.edu)
.\" ------------
.TH BYTEORDER 3 1993-04-15 "BSD" "Podrêcznik programisty Linuksa"
.SH NAZWA
htonl, htons, ntohl, ntohs \- konwersja warto¶ci pomiêdzy lokalnym a
sieciowym porz±dkiem bajtów
.SH SK£ADNIA
.nf
.B #include <netinet/in.h>
.sp
.BI "uint32_t htonl(uint32_t " hostlong );
.sp
.BI "uint16_t htons(uint16_t " hostshort );
.sp
.BI "uint32_t ntohl(uint32_t " netlong );
.sp
.BI "uint16_t ntohs(uint16_t " netshort );
.fi
.SH OPIS
Funkcja \fBhtonl()\fP przekszta³ca warto¶æ long integer \fIhostlong\fP z
lokalnego na sieciowy porz±dek bajtów.
.PP
Funkcja \fBhtons()\fP przekszta³ca warto¶æ short integer \fIhostshort\fP z
lokalnego na sieciowy porz±dek bajtów.
.PP
Funkcja \fBntohl()\fP przekszta³ca warto¶æ long integer \fInetlong\fP z
sieciowego na lokalny porz±dek bajtów.
.PP
Funkcja \fBntohs()\fP przekszta³ca warto¶æ short integer \fInetshort\fP z
sieciowego na lokalny porz±dek bajtów.
.PP
W lokalnym porz±dku bajtów na platformie i80x86 pierwszy jest zawsze najmniej
znacz±cy bajt, w sieciowym porz±dku bajtów, u¿ywanym w Internecie, pierwszy
jest zawsze najbardziej znacz±cy bajt.
.SH "ZGODNE Z"
BSD 4.3
.SH "ZOBACZ TAK¯E"
.BR gethostbyname (3),
.BR getservent (3)
