.\" {PTM/AB/0.1/15-12-1998/"ctermid - pobranie nazwy terminalu kontroluj±cego"}
.\" t³umaczenie Adam Byrtek (abyrtek@priv.onet.pl)
.\" Aktualizacja do man-pages 1.55 - A. Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" ------------
.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 19:51:06 1993 by Rik Faith (faith@cs.unc.edu)
.\" ------------
.TH CTERMID 3 1993-04-06 "GNU" "Podrêcznik programisty Linuksa"
.SH NAZWA
ctermid \- pobranie nazwy terminala kontroluj±cego proces
.SH SK£ADNIA
.nf
.B #include <stdio.h>
.sp
.BI "char *ctermid(char *" "s" );
.fi
.SH OPIS
Funkcja
.B ctermid()
zwraca ³añcuch, który jest ¶cie¿k± do terminala kontroluj±cego proces.
Je¶li
.I s
jest równe
.BR NULL ,
u¿ywany jest bufor statyczny, w przeciwnym wypadku
.I s
wskazuje na bufor maj±cy zawieraæ ¶cie¿kê do terminala.
Sta³a
.B L_ctermid
oznacza maksymaln± liczbê znaków w zwracanej ¶cie¿ce.
.SH "WARTO¦Æ ZWRACANA"
Wska¼nik do ¶cie¿ki.
.SH "ZGODNE Z"
SVID, wydanie 1; POSIX.1
.SH B£ÊDY
Zwracana ¶cie¿ka nie musi jednoznacznie identyfikowaæ
kontroluj±cego terminala; mo¿e to byæ na przyk³ad
.BR /dev/tty .
.PP
Nie jest pewne, czy program bêdzie móg³ otworzyæ ten terminal.
.SH "ZOBACZ TAK¯E"
.BR ttyname (3)
