.\" {PTM/AB/0.1/20-12-1998/"fflush - wypró¿nienie buforów strumienia"}
.\" translated by Adam Byrtek <abyrtek@priv.onet.pl>
.\" Aktualizacja do man-pages 1.47 - A. Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" ------------
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)fflush.3	5.4 (Berkeley) 6/29/91
.\"
.\" Converted for Linux, Mon Nov 29 15:22:01 1993, faith@cs.unc.edu
.\"
.\" Modified 2000-07-22 by Nicolás Lichtmaier <nick@debian.org>
.\" Modified 2001-10-16 by John Levon <moz@compsoc.man.ac.uk>
.\" ------------
.TH FFLUSH 3 1993-11-29 "BSD" "Podrêcznik programisty Linuksa"
.SH NAZWA
fflush \- wypró¿nienie buforów strumienia
.SH SK£ADNIA
.B #include <stdio.h>
.sp
.BI "int fflush(FILE *" stream );
.SH OPIS
Funkcja
.B fflush
wymusza zapis wszystkich buforowanych danych dla danego strumienia wyj¶ciowego
.I stream
poprzez podleg³± strumieniowi funkcjê zapisu. Stan strumienia nie jest
zmieniany, jest on nadal otwarty.
.PP
Je¶li argument
.I stream
jest równy
.BR NULL ,
.B fflush
wypró¿nia
.I wszystkie
otwarte strumienie wyj¶ciowe.
Informacje o nieblokuj±cym odpowiedniku znajduj± siê w
.BR unlocked_stdio (3).
.SH "WARTO¦Æ ZWRACANA"
Je¶li funkcja zakoñczy³a siê pomy¶lnie zwracane jest 0. W przeciwnym
przypadku zwracana jest warto¶æ
.BR EOF ,
a zmienna globalna
.I errno
przyjmuje warto¶æ okre¶laj±c± rodzaj b³êdu.
.SH B£ÊDY
.TP
.B EBADF
Strumieñ
.I stream
nie jest otwarty lub nie jest otwarty do zapisu.
.PP
Funkcja
.B fflush()
mo¿e tak¿e zawie¶æ i ustawiæ warto¶æ
.I errno
na dowolny b³±d wymieniony w opisie funkcji
.BR write (2).
.SH UWAGI
Nale¿y zauwa¿yæ, ¿e
.B fflush
opró¿nia jedynie bufory w przestrzeni u¿ytkownika obs³ugiwane przez
bibliotekê C. Aby upewniæ siê, ¿e dane zosta³y fizycznie zapisane na
dysku, nale¿y zrzuciæ rownie¿ bufory j±dra, np. za pomoc±
.BR sync (2)
lub
.BR fsync (2).
.SH "ZGODNE Z"
Funkcja
.BR fflush()
jest zgodna ze standardem ANSI X3.159-1989 (``ANSI C'').
.SH "ZOBACZ TAK¯E"
.BR fsync (2),
.BR sync (2),
.BR write (2),
.BR fclose (3),
.BR fopen (3),
.BR setbuf (3),
.BR unlocked_stdio (3)
