.\" {PTM/AB/0.1/13-03-1999/""}
.\" translated by Adam Byrtek <alpha@irc.pl>
.\" Aktualizacja do man-pages 1.45 - A. Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" ------------
.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Wed Jul 28 11:12:26 1993 by Rik Faith (faith@cs.unc.edu)
.\" ------------
.TH FPATHCONF 3  "1993-04-04" "GNU" "Podrêcznik programisty Linuksa"
.SH NAZWA
fpathconf, pathconf \- pobranie konfiguracji dla plików
.SH SK£ADNIA
.nf
.B #include <unistd.h>
.sp
.BI "long fpathconf(int " filedes ", int " name );
.nl
.BI "long pathconf(char *" path ", int " name );
.fi
.SH OPIS
Funkcja
.B fpathconf()
pobiera warto¶æ opcji konfiguracyjnej
.I name
dla otwartego deskryptora pliku
.IR filedes .
.PP
Funkcja
.B pathconf()
pobiera warto¶æ opcji konfiguracyjnej
.I name
dla
pliku o nazwie
.IR path .
.PP
Odpowiednie makra, zdefiniowane w
.BR <unistd.h> ,
s± warto¶ciami minimalnymi. Je¶li aplikacja chce korzystaæ z warto¶ci, które
mog± siê zmieniaæ, to mo¿e wywo³aæ
.B fpathconf()
lub
.BR pathconf() ,
które zwracaj± bardziej liberalne wyniki.
.PP
Ustawianie jednej z poni¿szych sta³ych jako warto¶ci
.IR name ,
zwraca nastêpuj±ce opcje konfiguracji:
.TP
.B _PC_LINK_MAX
zwraca maksymaln± liczbê dowi±zañ do pliku. Je¶li
.I filedes
lub
.I path
odnosz±  siê do katalogu, to warto¶æ dotyczy ca³ego katalogu.
Odpowiadaj±ce temu makro to
.BR _POSIX_LINK_MAX .
.TP
.B _PC_MAX_CANON
zwraca maksymaln± d³ugo¶æ sformatowanej linii wej¶ciowej, przy czym
.I filedes
lub
.I path
musi odnosiæ siê do terminala.
Odpowiadaj±ce temu makro to
.BR _POSIX_MAX_CANON .
.TP
.B _PC_MAX_INPUT
zwraca maksymaln± d³ugo¶æ linii wej¶ciowej, przy czym
.I filedes
lub
.I path
musi odnosiæ siê do terminala.
Odpowiadaj±ce temu makro to
.BR _POSIX_MAX_INPUT .
.TP
.B _PC_NAME_MAX
zwraca maksymaln± d³ugo¶æ nazwy pliku w katalogu
.I path
lub
.IR filedes ,
jak± proces mo¿e utworzyæ. Odpowiadaj±ce temu makro to
.BR _POSIX_NAME_MAX .
.TP
.B _PC_PATH_MAX
zwraca maksymaln± d³ugo¶æ wzglêdnej ¶cie¿ki, gdy
.I path
lub
.I filedes
jest katalogiem bie¿±cym. Odpowiadaj±ce temu makro to
.BR _POSIX_PATH_MAX .
.TP
.B _PC_PIPE_BUF
zwraca rozmiar bufora ³±cza komunikacyjnego (pipe), przy czym
.I filedes
musi odnosiæ siê do FIFO lub ³±cza, a
.I path
musi odnosiæ siê do FIFO. Odpowiadaj±ce temu makro to
.BR _POSIX_PIPE_BUF .
.TP
.B _PC_CHOWN_RESTRICTED
zwraca warto¶æ niezerow± je¶li wywo³anie
.BR chown (2)
nie mo¿e byæ zastosowane do tego pliku. Je¶li
.I filedes
lub
.I path
odnosz± siê do katalogu, to dotyczy to wszystkich plików w tym
katalogu. Odpowiadaj±ce temu makro to
.BR _POSIX_CHOWN_RESTRICTED .
.TP
.B _PC_NO_TRUNC
zwraca warto¶æ niezerow± je¶li dostêp do plików o nazwach d³u¿szych od
.B _POSIX_NAME_MAX
powoduje b³±d. Odpowiadaj±ce temu makro to
.BR _POSIX_NO_TRUNC .
.TP
.B _PC_VDISABLE
zwraca warto¶æ niezerow± je¶li przetwarzanie znaków specjalnych mo¿e byæ
wy³±czone, przy czym
.I filedes
lub
.I path
musz± odnosiæ siê do terminala.
.SH "WARTO¦Æ ZWRACANA"
Je¶li istnieje ograniczenie, to jest ono zwracane. Je¶li system dla danego
zasobu nie ma ograniczenia, zwracane jest \-1 a
.I errno
pozostaje niezmienione. Je¶li wyst±pi b³±d, zwracane jest \-1 a
ustawienie
.I errno
okre¶la charakter b³êdu.
.SH "ZGODNE Z"
POSIX.1
.SH UWAGI
W danym katalogu mog± istnieæ pliki o nazwach d³u¿szych ni¿ warto¶æ
zwrócona dla
.I name
równego
.BR _PC_NAME_MAX .
.PP
Niektóre ze zwracanych warto¶ci mog± byæ olbrzymie, nie nadaj± siê one do
alokowania pamiêci.
.SH "ZOBACZ TAK¯E"
.BR getconf (1),
.BR statfs (2),
.BR open (2),
.BR sysconf (3)
