.\" Tłumaczenie na podstawie wersji man-pages 1.45
.\" Andrzej Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" ------------
.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH FPUTWS 3 1999-07-25 "GNU" "Podręcznik programisty Linuksa"
.SH NAZWA
fputws \- zapisanie łańcucha szerokich znaków do strumienia FILE
.SH SKŁADNIA
.nf
.B #include <wchar.h>
.sp
.BI "int fputws(const wchar_t *" ws ", FILE *" stream );
.fi
.SH OPIS
\fI Uwaga! To tłumaczenie może być nieaktualne!\fP
.PP
Funkcja \fBfputws\fP jest szerokoznakowym odpowiednikiem funkcji \fBfputs\fP.
Zapisuje ona do \fIstream\fP łańcuch szerokich znaków o początku wskazywanym
przez \fIws\fP, aż do, ale z wyłączeniem, kończącego znaku L'\\0'.
.PP
Informacje o nieblokującym odpowiedniku znajdują się w
.BR unlocked_stdio (3).
.SH "WARTOŚĆ ZWRACANA"
Funkcja \fBfputws\fP zwraca nieujemną liczbę całkowitą, gdy nie wystąpił błąd,
a \-1 aby zasygnalizować wystąpienie błędu.
.SH "ZGODNE Z"
ISO/ANSI C, UNIX98
.SH UWAGI
Zachowanie \fBfputws\fP zależy od ustawienia kategorii LC_CTYPE aktualnego
locale.
.PP
W przypadku nieprzekazania dodatkowych informacji przy wywołaniu fopen,
ozsądne jest oczekiwanie, że \fBfputws\fP faktycznie zapisze wielobajtowy
ciąg odpowiadający łańcuchowi szerokich znaków \fIws\fP.
.SH "ZOBACZ TAKŻE"
.BR fputwc (3)
.BR unlocked_stdio (3)
.SH "INFORMACJE O TŁUMACZENIU"
Powyższe tłumaczenie pochodzi z nieistniejącego już Projektu Tłumaczenia Manuali i 
\fImoże nie być aktualne\fR. W razie zauważenia różnic między powyższym opisem
a rzeczywistym zachowaniem opisywanego programu lub funkcji, prosimy o zapoznanie 
się z oryginalną (angielską) wersją strony podręcznika za pomocą polecenia:
.IP
man \-\-locale=C 3 fputws
.PP
Prosimy o pomoc w aktualizacji stron man \- więcej informacji można znaleźć pod
adresem http://sourceforge.net/projects/manpages\-pl/.
