.\" T³umaczenie na podstawie wersji man-pages 1.47 - grudzieñ 2001
.\" Andrzej Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" ------------
.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\" ------------
.TH FWIDE 3  1999-11-17 "GNU" "Podrêcznik programisty Linuksa"
.SH NAZWA
fwide \- ustawienie i okre¶lenie orientacji strumienia FILE
.SH SK£ADNIA
.nf
.B #include <wchar.h>
.sp
.BI "int fwide(FILE *" stream ", int " mode );
.fi
.SH OPIS
Gdy \fImode\fP jest zerem, funkcja \fBfwide\fP podaje aktualn± orientacjê
strumienia \fIstream\fP. Zwraca ona warto¶æ > 0, gdy \fIstream\fP jest
zorientowany szerokoznakowo, tzn. gdy we/wy dla szerokich znaków jest
dozwolone, a we/wy dla znaków typu char nie jest dozwolone. Warto¶æ < 0
zwraca, gdy \fIstream\fP jest zorientowany bajtowo, tzn. gdy we/wy dla znaków
typu char jest dozwolone, a we/wy dla szerokich znaków nie jest dozwolone.
Zero jest zwracane, gdy strumieñ \fIstream\fP nie posiada jeszcze orienatcji;
w tym przypadku nastêpna operacja we/wy mo¿e zmieniæ orientacjê (na bajtow±,
je¶li bêdzie to operacja we/wy dla znaków typu char, a na szerokoznakow±,
je¶li bêdzie to operacja we/wy dla szerokich znaków).
.PP
Raz uzyskana przez strumieñ orientacja nie mo¿e zostaæ zmieniona a¿ do
zamkniêcia strumienia.
.PP
Gdy \fImode\fP jest ró¿ne od zera, to funkcja \fBfwide\fP najpierw próbuje
ustawiæ orientacjê strumienia \fIstream\fP (na szerokoznakow±, gdy
\fImode\fP > 0, a na bajtow±, gdy \fImode\fP < 0). Nastêpnie zwraca warto¶æ
okre¶laj±c± aktualn± orientacjê, jak powy¿ej.
.SH "WARTO¦Æ ZWRACANA"
Funkcja \fBfwide\fP zwraca orientacjê strumienia, po jej ewentualnej zmianie.
Zwrócenie warto¶ci > 0 oznacza orientacjê szerokoznakow±. Zwrócenie warto¶ci
< 0 oznacza orientacjê bajtow±. Zwrócenie warto¶ci zero oznacza orientacjê
nieokre¶lon±.
.SH "ZGODNE Z"
ISO/ANSI C, UNIX98
.SH "ZOBACZ TAK¯E"
.BR fprintf (3),
.BR fwprintf (3)
.SH UWAGI
Wyprowadzanie szerokich znaków do zorientowanego bajtowo strumienia mo¿e byæ
wykonane za pomoc± funkcji \fBfprintf\fP przy u¿yciu dyrektyw %lc i %ls.
.PP
Wyprowadzanie zorientowane na znakoi typu char do zorientowanego
szerokoznakowo strumienia mo¿e byæ wykonane za pomoc± funkcji \fBfwprintf\fP
przy u¿yciu dyrektyw %c i %s.
