.\" Translation: Robert Luberda <robert@debian.org>, Oct 2003, manpages 1.60
.\" $Id: getrpcport.3,v 1.3 2004/10/09 14:51:29 robert Exp $
.\"
.\" @(#)getrpcport.3r	2.2 88/08/02 4.0 RPCSRC; from 1.12 88/02/26 SMI
.TH GETRPCPORT 3R 1987-10-06 
.SH NAZWA
getrpcport \- zwraca numer portu RPC
.SH SK£ADNIA
.ft B
.nf
int getrpcport(host, prognum, versnum, proto)
	char *host;
	int prognum, versnum, proto;
.fi
.SH OPIS
.B getrpcport()
zwraca numer portu dla wersji
.I versnum
programu RPC
.IR prognum ,
dzia³aj±cego na komputerze
.IR host ,
u¿ywaj±cego protoko³u
.IR proto .
Funkcja zwraca 0, je¿eli nie mo¿e skontaktowaæ siê z portmapperem
albo je¿eli program
.I prognum
nie jest zarejestrowany. Je¿eli
.I prognum
zosta³ zarejestrowany, ale nie w wersji
.IR versnum ,
funkcja wci±¿ zwróci numer portu (jakiej¶ innej wersji programu),
sygnalizuj±c, ¿e program jest zarejestrowany.
Niedopasowanie wersji zostanie wykryte przy pierwszym odwo³aniu do serwisu.
