.\" T³umaczenie wersji man-pages 1.39 - wrzesieñ 2001 PTM
.\" Aktualizacja do man-pages 1.47 - styczeñ 2002
.\" Andrzej Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" --------
.\" Copyright 2001 Andries Brouwer <aeb@cwi.nl>.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" --------
.TH ROUND 3  2001-05-31 "" "Podrêcznik programisty Linuksa"
.SH NAZWA
round, roundf, roundl \- zaokr±glenie do najbli¿szej liczby ca³kowitej
z omijaniem zera
.SH SK£ADNIA
.nf
.B #include <math.h>
.sp
.BI "double round(double " x );
.br
.BI "float roundf(float " x );
.br
.BI "long double roundl(long double " x );
.fi
.SH OPIS
Funkcje te zaokr±glaj± \fIx\fP do najbli¿szej liczby ca³kowitej, ale
w okolicy zera omijaj± zero (niezale¿nie od aktualnego kierunku zaokr±glania)
zaokr±glaj±c, jak rint(), do najbli¿szej liczby nieparzystej.
.SH "WARTO¦Æ ZWRACANA"
Warto¶æ ca³kowita bêd±ca wynikiem zaokr±glenia. Je¶li \fIx\fP jest ca³kowite
lub nieskoñczone, zwracana jest warto¶æ \fIx\fP.
.SH B£ÊDY
Nie mog± wyst±piæ ¿adne b³êdy oprócz EDOM i ERANGE.
Je¶li \fIx\fP wynosi NaN, to zwracana jest warto¶æ NaN i
.I errno
mo¿e byæ ustawione na EDOM.
.SH UWAGI
POSIX 1003.1-2001 zawiera tekst dotycz±cy przepe³nienia (które mo¿e spowodowaæ
ustawienie
.I errno
na ERANGE lub spowodowaæ wyj±tek).
W praktyce wynik nie mo¿e spowodowaæ przepe³nienia na ¿adnej wspó³czesnej
maszynie, wiêc obs³uga tego b³êdu jest po prostu bezsensowna.
(Dok³adniej, przepe³nienie mo¿e wyst±piæ tylko gdy warto¶æ maksymalna
wyk³adnika jest mniejsza ni¿ liczba bitów mantysy.
Wed³ug standardu IEEE-754 dla 32 i 64-bitowych liczb zmiennoprzecinkowych
warto¶æ maksymalna wyk³adnika wynosi 128 (odp. 1024), a liczba bitów mantysy
wynosi 24 (odp. 53).)
.SH "ZGODNE Z"
C99.
.SH "ZOBACZ TAK¯E"
.BR ceil (3),
.BR floor (3),
.BR lround (3),
.BR nearbyint (3),
.BR rint (3),
.BR trunc (3)
