.\" Translation (c) 1999 Pawel Wilk <siewca@dione.ids.pl>
.\" {PTM/PW/0.1/16-06-1999/"zwróæ ci±g opisuj±cy sygna³"}
.\" Aktualizacja do man-pages 1.47 - A. Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" --------
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:59:03 1993 by Rik Faith (faith@cs.unc.edu)
.\" --------
.TH STRSIGNAL 3 1999-02-08 "GNU" "Podrêcznik Programisty Linuksa"
.SH NAZWA
strsignal \- zwraca napis opisuj±cy sygna³
.SH SK£ADNIA
.nf
.B #define _GNU_SOURCE
.br
.B #include <string.h>
.sp
.BI "char *strsignal(int " sig );
.sp
.BI "extern const char * const " sys_siglist [];
.fi
.SH OPIS
Funkcja \fBstrsignal()\fP zwraca ³añcuch opisuj±cy numer sygna³u 
przekazany w argumencie \fIsig\fP. £añcuch mo¿e byæ u¿ywany tylko
do nastêpnego wywo³ania funkcji \fBstrsignal()\fP.
.PP
Tablica \fIsys_siglist\fP przechowuje ³añcuchy opisuj±ce sygna³y
poindeksowane wed³ug numerów sygna³ów. O ile jest to mo¿liwe, nale¿y raczej
korzystaæ z funkcji \fBstrsignal()\fP, ni¿ z bezpo¶redniego dostêpu do tej
tablicy.
.SH "WARTO¦Æ ZWRACANA"
Funkcja \fBstrsignal()\fP zwraca odpowiedni ³añcuch opisu lub komunikat
o nieznanym sygnale, gdy numer sygna³u jest b³êdny. W niektórych systemach
(ale nie w Linuksie), dla b³êdnego numeru sygna³u mo¿e zostaæ zwrócony,
zamiast komunikatu, wska¼nik o warto¶ci \fBNULL\fP.
.SH "ZGODNE Z"
Funkcja ta nie wchodzi w sk³ad ¿adnego standardu. Mo¿na j± jednak znale¼æ
w systemach linuksowych i niektórych systemach uniksowych (np. w Solarisie).
.SH "ZOBACZ TAK¯E"
.BR psignal (3),
.BR strerror (3)
