.\" Hey Emacs! This file is -*- nroff -*- source.
.\" 
.\" T³umaczenie wersji man-pages 1.39 - wrzesieñ 2001 PTM
.\" Andrzej Krzysztofowicz <ankry@mif.pg.gda.pl>
.\" --------
.\" (c) 1995 by Jim Van Zandt <jrv@vanzandt.mv.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\"
.\" Added BUGS section, aeb, 950919
.\" --------
.TH TOASCII 3  1995-09-16 "GNU" "Podrêcznik programisty Linuksa"
.SH NAZWA
toascii \- przekszta³ca znak na ASCII
.SH SK£ADNIA
.nf
.B #include <ctype.h>
.sp
.BI "int toascii(int " "c" );
.fi
.SH OPIS
\fBtoascii\fP() przekszta³ca \fIc\fP na 7-bitow± warto¶æ typu
\fBunsigned char\fP, która nale¿y do zestawu znaków ASCII, poprzez wyzerowanie
najbardziej znacz±cych bitów.
.SH "WARTO¦Æ ZWRACANA"
Zwracana jest warto¶æ przekszta³conego znaku.
.SH "ZGODNE Z"
SVID, BSD
.SH B£ÊDY
Wiele osób bêdzie niezadowolonych, je¶li u¿yjesz tej funkcji.
Przekszta³ca ona litery akcentowane na przypadkowe znaki.
.SH "ZOBACZ TAK¯E"
.BR isascii (3),
.BR toupper (3),
.BR tolower (3)
