.\" 2002 PTM Przemek Borys <pborys@dione.ids.pl>
.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"
.TH WCPCPY 3  1999-07-25 "GNU" "Podrêcznik programisty linuksowego"
.SH NAZWA
wcpcpy \- kopiuje ³añcuch szerokich znaków i zwraca wska¼nik do jego koñca
.SH SK£ADNIA
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcpcpy(wchar_t *" dest ", const wchar_t *" src );
.fi
.SH OPIS
Funkcja \fBwcpcpy\fP jest odpowiednikiem \fBstpcpy\fP dla szerokich znaków.
Kopiuje ³añcuch znaków z \fIsrc\fP (³±cznie z koñcz±cym L'\\0') do tablicy
wskazanej przez \fIdest\fP.
.PP
£añcuchy nie mog± na siebie zachodziæ.
.PP
Programista musi zapewniæ, ¿e w \fIdest\fP jest do¶æ miejsca przynajmniej na
\fIwcslen(src)+1\fP szerokich znaków.
.SH "WARTO¦Æ ZWRACANA"
\fBwcpcpy\fP zwraca wska¼nik do koñca ³añcucha szerokich znaków w \fIdest\fP,
tzn. wska¼nik do koñcz±cego znaku L'\\0'.
.SH "ZGODNE Z"
Funkcja ta jest rozszerzeniem GNU.
.SH "ZOBACZ TAK¯E"
.BR strcpy (3),
.BR wcscpy (3)
