.\" Translation (c) 1999 Pawel Wilk <siefca@pl.qmail.org>
.\" {PTM/PW/0.1/10-11-1999/"przegl±d dokumentacji qmail"}
.TH qmail 7
.SH "NAZWA"
qmail \- przegl±d dokumentacji qmail
.SH "WPROWADZENIE"
.B qmail
jest bezpiecznym, sprawnym, efektywnym, prostym agentem przesy³ania poczty.

U¿ytkownicy, którzy chc± mieæ pe³n± kontrolê nad przychodz±cymi wiadomo¶ciami
powinni przeczytaæ podrêcznik
.BR dot-qmail (5).
Pomocne w korzystaniu z pliku
.B .qmail
komendy to
.BR qbiff (1),
.BR qreceipt (1),
.BR qforward (1),
.BR bouncesaying (1),
i
.BR condredirect (1).
Inne po¿yteczne komendy to
.BR maildirmake (1),
.BR maildir2mbox (1),
i
.BR maildirwatch (1).

Administrator systemu chc±cy kontrolowaæ ca³y system poczty
.B qmail
powinien zacz±æ od przeczytania
.BR qmail-control (5)
i
.BR qmail-start (8).
S± te¿ trzy narzêdzia s³u¿±ce do monitorowania kolejki poczty:
.BR qmail-qread (8),
.BR qmail-qstat (8),
i
.BR qmail-tcpto (8).
Nadchodz±ce po³±czenia SMTP s± obs³ugiwane przez
.BR qmail-smtpd (8).

.B qmail
oferuje dwa interfejsy w postaci komend do wysy³ania wiadomo¶ci:
.BR qmail-inject (8)
i
.BR mailsubj (1).
By uzyskaæ szczegó³owe informacje na temat internetowych wiadomo¶ci pocztowych
przejrzyj podrêczniki
.BR addresses (5),
.BR envelopes (5),
.BR qmail-header (5),
i
.BR forgeries (7).

Dodatkowa dokumentacja zawiera
.BR qmail-limits (7)
i
.BR qmail-pop3d (8).

Dokumentacja ta opisuje wersjê
1.03
systemu
.BR qmail .
Obejrzyj
.B http://pobox.com/~djb/qmail.html
by zapoznaæ siê z innymi programami wspó³dzia³aj±cymi z 
.BR qmail .
