.\" {PTM/PB/0.1/02-02-1999/"Serwer httpd apache"}
.\" Translation 1999 Przemek Borys <pborys@dione.ids.pl>
.TH httpd 1m "Pa¼dziernik 1995"
.\" Copyright (c) 1995 David Robinson. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" 3. All advertising materials mentioning features or use of this
.\"    software must display the following acknowledgment:
.\"    "This product includes software developed by the Apache Group
.\"    for use in the Apache HTTP server project (http://www.apache.org/)."
.\"
.\" 4. The names "Apache Server" and "Apache Group" must not be used to
.\"    endorse or promote products derived from this software without
.\"    prior written permission.
.\"
.\" 5. Redistributions of any form whatsoever must retain the following
.\"    acknowledgment:
.\"    "This product includes software developed by the Apache Group
.\"    for use in the Apache HTTP server project (http://www.apache.org/)."
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE APACHE GROUP ``AS IS'' AND ANY
.\" EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE APACHE GROUP OR
.\" ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
.\" OF THE POSSIBILITY OF SUCH DAMAGE.
.\" ====================================================================
.\"
.\" This software consists of voluntary contributions made by many
.\" individuals on behalf of the Apache Group and was originally based
.\" on public domain software written at the National Center for
.\" Supercomputing Applications, University of Illinois, Urbana-Champaign.
.\" For more information on the Apache Group and the Apache HTTP server
.\" project, please see <http://www.apache.org/>.
.SH NAZWA
httpd \- serwer http Apache
.SH SK£ADNIA
.B httpd 
[
.B \-vX?
] [
.BI \-d " serverroot"
] [
.BI \-f " config"
]
.SH OPIS
.B httpd
jest serwerem HTTP Apache. Serwer mo¿e byæ wywo³ywany przez demona
internetowego inetd(1M) za ka¿dym razem, gdy zaistnieje po³±czenie HTTP, lub
w innym wypadku dzia³aæ jako demon.
.SH OPCJE
.TP 12
.BI \-d " serverroot"
Ustaw pocz±tkow± warto¶æ zmiennej ServerRoot na \fIserverroot\fP. Mo¿e to
byæ przedefiniowane przez komendê ServerRoot w pliku konfiguracyjnym.
Domy¶lnym jest \fB/etc/httpd\fP.
.TP
.BI \-f " config"
Wywo³aj na starcie komendy z pliku \fIconfig\fP. Je¶li \fIconfig\fP nie
zaczyna siê od /, to jest uznawany za relatywny w ¶cie¿ce do ServerRoot.
Domy¶lnym jest \fBconf/httpd.conf\fP.
.TP
.B \-X
Pracuj w trybie pojedynczo procesowym, jedynie w celach wewnêtrzno
debuggowych; demon nie od³±cza siê od terminala ani nie robi ¿adnych dzieci ;)
(forkuje to znaczy ;). NIE u¿ywaj tego trybu do udostêpniania zwyk³ych us³ug
WWW.
.TP
.B \-v
Wydrukuj wersjê httpd i zakoñcz.
.TP
.B \-?
Wydrukuj listê opcji httpd i zakoñcz.
.SH PLIKI
.PD 0
.B /etc/httpd/conf/httpd.conf
.br
.B /etc/httpd/conf/srm.conf
.br
.B /etc/httpd/conf/access.conf
.br
.B /etc/httpd/conf/mime.types
.br
.B /var/log/httpd/error_log
.br
.B /var/log/httpd/access_log
.br
.B /var/run/httpd.pid
.PD
.SH ZOBACZ TAK¯E
.BR inetd (1m).
.PP
Dokumentacja serwera Apache jest dostêpna z
http://www.apache.org/
