.TH IPTABLES-SAVE 8 "Jan 04, 2001" "" ""
.\"
.\" Man page written by Harald Welte <laforge@gnumonks.org>
.\" It is based on the iptables man page.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAZWA
iptables-save \- Zapisuje tabele IP
.SH SK£ADNIA
.BR "iptables-save " "[-c] [-t table]"
.br
.SH OPIS
.PP
.B iptables-save
jest u¿ywany w celu zrzucenia zawarto¶ci tabeli IP w prostym parsowalnym formacie
na standardowe wyj¶cie (STDOUT). U¿ywa przekierowania wej¶cia wyj¶cia dostarczanego przez twoj± pow³okê aby zapisaæ do pliku.
.TP
\fB\-c\fR, \fB\-\-counters\fR
do³±cza aktualne warto¶ci wszystkich pakietów i liczników bajtów na wyj¶cie
.TP
\fB\-t\fR, \fB\-\-table\fR \fBtablename\fR
.TP
ogranicza wyj¶cie tylko do jednej tabeli. Je¶li nie podano wyj¶cie zawiera wszystkie
dostepne tabele.
.SH B£ÊDY
Nie znane dla wersji iptables-1.2.1
.SH AUTOR
Harald Welte <laforge@gnumonks.org>
.SH ZOBACZ RÓWNIE¯
.BR iptables-restore "(8), " iptables "(8) "
.PP
iptables-HOWTO, które podaje wiêcej na temat u¿ycia iptables , NAT-HOWTO,
które podaje szczegó³y na temat NAT i netfilter-hacking-HOWTO które podaje szczegó³y
na temat ograniczeñ.
