.\" {PTM/WK/1999-XII}
.\" -*- nroff -*-
.TH MKDOSFS 8 "27 lutego 1997" "Version 0.4"
.SH NAZWA
.B mkdosfs
\- pod kontrol± Linuksa twórz system plików FAT
.SH SK£ADNIA
.B mkdosfs
.RB [ \-c | \-l
.IR filename ]
.RB [ \-f
.IR number-of-FATs ]
.RB [ \-F
.IR FAT-size ]
.RB [ \-i
.IR volume-id ]
.RB [ \-m
.IR message-file ]
.RB [ \-n
.IR volume-name ]
.RB [ \-r
.IR root-dir-entries ]
.RB [ \-s
.IR sectors-per-cluster ]
.RB [ \-v ]
.I device
.RI [ block-count ]
.SH OPIS
.B mkdosfs
s³u¿y do tworzenia, pod kontrol± Linuksa, systemu plików MS-DOS na zadanym
urz±dzeniu (zwykle partycji dysku).
By utworzyæ partycjê
.BR FAT32 ,
pos³u¿ siê opcj±
.IR "-F 32" .
.PP
.I device
jest plikiem specjalnym odpowiadaj±cym danemu urz±dzeniu (np. /dev/hdXX).
.PP
.I block-count
jest liczb± bloków urz±dzenia. Je¶li pominiêto, to
.B mkdosfs
automatycznie okre¶la rozmiar systemu plików.
.SH OPCJE
.TP
.B \-c
Sprawd¼ obecno¶æ b³êdnych bloków na urz±dzeniu przed tworzeniem systemu plików.
.TP
.BI \-f " number-of-FATs"
Okre¶l liczbê tablic alokacji plików (FAT) w systemie plików. Domy¶lnie 2.
Obecnie linuksowy system plików MS-DOS nie obs³uguje wiêcej ni¿ dwu tablic
FAT.
.TP
.BI \-F " FAT-size"
Okre¶la typ u¿ywanej tablicy alokacji plików (12-, 16-, lub 32-bitowa). Opcja
wymagana do utworzenia partycji
.BR FAT32 .
W przeciwnym razie, nie jest zwykle przydatna, gdy¿
.B mkdosfs
automatycznie wybiera zalecany rozmiar FAT dla danego systemu plików.
.TP
.BI \-i " volume-id"
Ustawia identyfikator wolumenu nowo utworzonego systemu plików;
.I volume-id
jest 32-bitow± liczb± szesnastkow± (na przyk³ad, 2e24ec82). Domy¶lnie jest to
liczba zale¿na od czasu utworzenia systemu plików.
.TP
.BI \-l " filename"
Odczytaj listê b³êdnych bloków z pliku o nazwie
.IR filename .
.TP
.BI \-m " message-file"
Ustawia komunikat, jaki otrzymuje u¿ytkownik podczas próby startu (boot)
tego systemu plików bez poprawnie zainstalowanego systemu operacyjnego.
Komunikat nie mo¿e przekraczaæ 418 bajtów po konwersji znaków koñca linii
na kombinacje powrót karetki-koniec linii i rozwiniêciu znaków tabulacji.
Je¿eli nazw± pliku jest my¶lnik (-), to tekst jest pobierany ze standardowego
wej¶cia.
.TP
.BI \-n " volume-name"
Ustawia nazwê wolumenu (etykietê - label) systemu plików. Nazwa wolumenu mo¿e
mieæ d³ugo¶æ do 11 znaków. Domy¶lnie brak etykiety.
.TP
.BI \-r " root-dir-entries"
Okre¶la liczbê pozycji dostêpnych w g³ównym katalogu. Domy¶lnie jest to 112
lub 224 dla dyskietek oraz 512 dla dysków twardych.
.TP
.BI \-s " sectors-per-cluster"
Okre¶la liczbê sektorów dysku przypadaj±cych na jeden cluster. Musi byæ
potêg± 2, tj. 1, 2, 4, 8, ... 128.
.TP
.B \-v
Wykonywanie gadatliwe.
.SH B£ÊDY
Na razie nie s± znane. Je¶li jakie¶ znajdziesz, proszê zg³o¶ je
[w jêz.angielskim]
na adres <chaffee@bmrc.berkeley.edu>. Do³±cz, proszê, numer wersji (0.4).
.SH AUTOR
Dave Hudson <dave@humbug.demon.co.uk>; modyfikacje: Peter Anvin
<hpa@yggdrasil.com>; obs³ugê FAT32 doda³ Gordon Chaffee
<chaffee@bmrc.berkeley.edu>.
.SH PODZIÊKOWANIA
.B mkdosfs
oparty jest o kod z
.BR mke2fs
(napisany przez: Remy Card - <card@masi.ibp.fr>), który z kolei oparto o
.BR mkfs 
(napisany przez: Linus Torvalds - <torvalds@cs.helsinki.fi>).
.SH ZOBACZ TAK¯E
.BR dosfsck (8),
.BR mkfs (8).
