.\" Translation (C) 1999 Pawel Wilk <siefca@pl.qmail.org>
.\" {PTM/PW/0.1/5-12-1999/"wyświetla wychodzące wiadomości i ich odbiorców"}
.TH qmail-qread 8
.SH NAZWA
qmail-qread \- wyświetl wychodzące wiadomości i ich odbiorców
.SH SKŁADNIA
.B qmail-qread
.SH OPIS
\fI Uwaga! To tłumaczenie może być nieaktualne!\fP
.PP
.B qmail-qread
skanuje kolejkę wychodzącą pod kątem znalezienia wiadomości.
Dla każdej wiadomości wypisuje różne informacje w formie zrozumiałej dla 
człowieka, włączając w to datę dostarczenia wiadomości do kolejki,
ilość bajtów wiadomości,
nadawcę wiadomości
i wszystkich wciąż branych pod uwagę odbiorców.

.B qmail-qread
musi być uruchomiony jako
.B root
albo z identyfikatorem użytkownika
.B qmails
i identyfikatorem grupy
.BR qmail .
.SH "ZOBACZ TAKŻE"
qmail-qstat(8),
qmail-send(8)
.SH "INFORMACJE O TŁUMACZENIU"
Powyższe tłumaczenie pochodzi z nieistniejącego już Projektu Tłumaczenia Manuali i 
\fImoże nie być aktualne\fR. W razie zauważenia różnic między powyższym opisem
a rzeczywistym zachowaniem opisywanego programu lub funkcji, prosimy o zapoznanie 
się z oryginalną (angielską) wersją strony podręcznika za pomocą polecenia:
.IP
man \-\-locale=C 8 qmail-qread
.PP
Prosimy o pomoc w aktualizacji stron man \- więcej informacji można znaleźć pod
adresem http://sourceforge.net/projects/manpages\-pl/.
