.\" Translation (C) 1999 Pawel Wilk <siefca@pl.qmail.org>
.\" {PTM/PW/0.1/5-12-1999/"podsumowanie statusu kolejki pocztowej"}
.TH qmail-qstat 8
.SH NAZWA
qmail-qstat \- podsumuj status kolejki pocztowej
.SH SK£ADNIA
.B qmail-qstat
.SH OPIS
.B qmail-qstat
zrzuca ilo¶æ wiadomo¶ci w poszczególnych miejscach pocztowej kolejki wiadomo¶ci
w zrozumia³ej dla cz³owieka formie.

.B qmail-qstat
musi byæ uruchomiony jako
.B root
lub z identyfikatorem grupy
.BR qmail .
.SH "ZOBACZ TAK¯E"
qmail-qread(8),
qmail-send(8)
