.\" Translation (C) 1999 Pawel Wilk <siefca@pl.qmail.org>
.\" {PTM/PW/0.1/14-06-1999/"przygotowuje przypisania adresów dla qmail-lspawn"}
.TH qmail-newu 8
.SH NAZWA
qmail-newu \- przygotuj przypisania adresów dla qmail-lspawn
.SH SK£ADNIA
.B qmail-newu
.SH OPIS
.B qmail-newu
czyta przypisania z
.B /var/qmail/users/assign
i zapisuje je do
.B /var/qmail/users/cdb
w formacie binarnym odpowiednim
dla szybkiego dostêpu przez
.BR qmail-lspawn .

Je¶li jest jaki¶ problem z plikiem
.BR users/assign ,
to
.B qmail-newu
wyja¶nia go i zostawia
.B users/cdb
w spokoju.

.B qmail-newu
dba o to by plik
.B users/cdb
by³ od¶wie¿any automatycznie,
wiêc
.B qmail-lspawn
nigdy nie musi czekaæ a¿
.B qmail-newu
skoñczy sw± pracê.
Jednak¿e,
.B qmail-newu
nie podejmuje próby ochrony przeciw sytuacji, w której
dwa niezale¿ne procesy od¶wie¿aj± zawarto¶æ
.BR users/cdb .

Format binarny
.B users/cdb
nadaje siê do przenoszenia pomiêdzy maszynami.

.SH "ZOBACZ TAK¯E"
qmail-users(5),
qmail-lspawn(8),
qmail-pw2u(8)
