.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\" 
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\" 
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\" 
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\" 
.\" Modified Sat Jul 24 17:00:12 1993 by Rik Faith (faith@cs.unc.edu)
.\" 
.\" T³umaczenie na jêzyk polski: Pawe³ Olszewski (alder@amg.net.pl)
.\" {PTM/PO/0.1/02-06-1998/"czarna dziura"}
.\" Aktualno¶æ: man-pages 1.48
.\" 
.TH NULL 4 1992-11-21 "Linux" "Podrêcznik Programisty Linuksa"
.SH NAZWA
null, zero \- czarna dziura
.SH OPIS
Dane zapisywane do plików specjalnych \fBnull\fP lub \fBzero\fP
przepadaj±.
.PP
Odczyt z pliku specjalnego \fBnull\fP zawsze zwraca znak koñca pliku,
podczas gdy odczyt z pliku \fBzero\fP zawsze zwraca znaki \e0.
.LP
\fBnull\fP i \fBzero\fP tworzone s± zazwyczaj poleceniami:
.RS
.sp
mknod -m 666 /dev/null c 1 3
.br
mknod -m 666 /dev/zero c 1 5
.br
chown root:mem /dev/null /dev/zero
.sp
.RE
.SH UWAGI
Je¶li niemo¿liwy jest zapis i odczyt z owych urz±dzeñ przez
wszystkich u¿ytkowników, wiele programów bêdzie siê zachowywaæ
dziwnie.
.SH PLIKI
.I /dev/null
.br
.I /dev/zero
.SH "ZOBACZ TAK¯E"
.BR chown (1),
.BR mknod (1)
