.\" 1999 PTM Przemek Borys
.\" poszerzenie i aktualizacja do GNU sh-utils 2.0 PTM/WK/2000-VI
.ig
Transl.note: based on GNU man page dirname.1 and sh-utils.info

Copyright (C) 1994, 95, 96 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be stated in a
translation approved by the Foundation.
..
.TH DIRNAME "1" FSF "maj 2000" "Narzêdzia pow³okowe GNU 2.0"
.SH NAZWA
dirname \- usuñ niekatalogowy przyrostek nazwy pliku
.SH SK£ADNIA
.B dirname
.I nazwapliku
.br
.B dirname
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH OPIS
Ta strona podrêcznika man opisuje polecenie \fBdirname\fR w wersji GNU.
.PP
.B dirname
wypisuje wszystkie, oprócz ostatniej, rozdzielone uko¶nikami sk³adowe
.IR nazwypliku .
Otrzymujemy w ten sposób ¶cie¿kê pliku.
Je¶li
.I nazwapliku
jest pojedyncz± sk³adow±,
.B dirname
wypisuje `\fB.\fP' (oznaczaj±ce bie¿±cy katalog).
.SH OPCJE
.TP
.B \-\-help
Wy¶wietla informacjê o stosowaniu programu i dostêpnych opcjach, koñczy
pracê.
.TP
.B \-\-version
Wy¶wietla numer wersji programu i koñczy pracê.
.SH "ZG£ASZANIE B£ÊDÓW"
B³êdy proszê zg³aszaæ, w jêz.ang., do <bug-sh-utils@gnu.org>.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH ZOBACZ TAK¯E
.BR basename (1),
.BR pathchk (1),
.BR sh-utils (1).
.SH OD T£UMACZA
Zaktualizowano i poszerzono wg dokumentacji Texinfo dla narzêdzi pow³okowych
GNU wersji 2.0.
