.\" {PTM/PR/0.1/28-07-1999/"narzêdzie oBs³ugi pakietów Debiana (.deb)"}
.\" $Id: dpkg-deb.1,v 1.4 2002/08/06 13:27:46 robert Exp $
.\" Translation 1999 by Piotr Roszatycki
.\" Last update: Robert Luberda <robert@debian.org>, Aug 2002, dpkg 1.10.4
.TH DPKG\-DEB 1 "1 lipca 1996" "Projekt Debiana" "u¿ytki dpkg"
.SH NAZWA
dpkg\-deb \- narzêdzie obs³ugi plików archiwum Debiana (.deb)
.SH SK£ADNIA
.B dpkg-deb
.BR -b | --build
.IR katalog " [" archiwum | katalog ]
.br
.B dpkg-deb
.BR -I | --info
.IR archiwum " [" nazwa\-pliku\-kontrolnego " ..]"
.br
.B dpkg-deb
.BR -f | --field
.IR archiwum " [" nazwa\-pola\-kontrolnego " ...]"
.br
.B dpkg-deb
.BR -c | --contents
.I archiwum
.br
.B dpkg-deb
.BR -x | --extract | -X | --vextract
.I archiwum katalog
.br
.B dpkg-deb --fsys-tarfile
.I archiwum
.br
.B dpkg-deb --control
.I archiwum katalog
.SH OPIS
.B dpkg-deb
tworzy, rozpakowuje i podaje informacje o plikach archiwum (czyli pakietach)
Debiana.

Do instalowania i usuwania pakietów z systemu s³u¿y polecenie
.BR dpkg .

Ponadto mo¿na skorzystaæ z
.B dpkg\-deb
wywo³uj±c
.B dpkg
z odpowiedni± opcj±, która zostanie przekazana do
.BR dpkg\-deb ".  " dpkg
uruchomi
.B dpkg\-deb
i wykona ¿±dan± operacjê.
.SH OPCJE DZIA£ANIA
.TP
.BR --build ", " -b
Tworzy archiwum Debiana z plików zawartych w
.IR katalogu ".  " katalog
musi zawieraæ podkatalog o nazwie
.BR DEBIAN ,
w którym zawarte s± pliki kontrolne, takie jak np. control. Ten katalog
.I nie
pojawi siê w archiwum binarnym pakietu, tylko zostanie umieszczony
jako informacje kontrolne pakietu, które opisuj± w³a¶ciwo¶ci pakietu.

Mo¿na podaæ poziom kompresji, u¿ywaj±c opcji
.BR \-z# .
dpkg-deb przeka¿e tê opcjê programowi gzip.

Je¶li pominiêto opcjê
.BR \-\-nocheck ", " dpkg\-deb
odczyta plik
.B DEBIAN/control
i sprawdzi, czy nie wystêpuj± w nim b³êdy sk³adniowe lub inne problemy,
a nastêpnie wy¶wietli nazwê pakietu, który jest tworzony.
.B dpkg\-deb
ponadto sprawdzi prawa skryptów instalacyjnych i innych plików znajduj±cych
siê w katalogu
.BR DEBIAN .

Je¶li podana zosta³a nazwa
.I archiwum
to
.B dpkg\-deb
zapisze pakiet t± nazw±.

Je¿eli taki pakiet ju¿ istnieje, zostanie on nadpisany.

Je¶li drugim argumentem jest 
.IR katalog ,
to
.B dpkg\-deb
zapisze pakiet pod nazw±
.IB katalog / pakiet _ wersja _ arch .deb\fR,
lub
.IB katalog / pakiet _ wersja .deb\fR,
je¶li nie zosta³o okre¶lone pole
.B Architecture
w pliku kontrolnym. Gdy podany jest
.IR katalog ,
to nie mo¿e zostaæ u¿yta opcja
.BR \-\-no\-check ,
poniewa¿ 
.B dpkg\-deb
musi odczytaæ plik kontrolny, aby rozpoznaæ nazwê i wersjê pakietu.
.TP
.BR \-\-info ", " -I
Dostarcza informacji o pakiecie.

Gdy nie podano ¿adnej
.IR nazwy\-pliku\-kontrolnego ,
wy¶wietlana jest informacja o zawarto¶ci pakietu oraz zestawienie
wykorzystanych plików kontrolnych.

W razie podania
.IR nazwy\-pliku\-kontrolnego ,
.B dpkg\-deb
wy¶wietli zawarto¶æ tego pliku. Je¶li ten plik nie istnieje, wy¶wietlony
zostanie komunikat b³êdu na stderr i program zakoñczy siê z kodem b³êdu 2.
.TP
.BR \-\-field ", " -f
Wy¶wietla zawarto¶æ pliku kontrolnego o nazwie control.

Je¶li nie podano ¿adnej
.BR nazwy\-pola\-kontrolnego ,
to wy¶wietlana jest zawarto¶æ ca³ego pliku control.

Je¶li podano
.BR nazwê\-pola\-kontrolnego ,
to
.B dpkg\-deb
wy¶wietli jej zawarto¶æ. Gdy podano wiêcej ni¿ jedn±
.BR nazwê\-pola\-kontrolnego ,
to 
.B dpkg\-deb
wy¶wietli pola wraz z nazw± (oraz dwukropkiem i spacj±)
w takiej kolejno¶ci, w jakiej s± one w pliku kontrolnym.

Dla nieodnalezionych pól kontrolnych nie wy¶wietlane s± komunikaty b³êdów.
.TP
.BR --contents ", " -c
Wy¶wietla zawarto¶æ archiwum. Wydruk jest podany w postaci, jak±
generuje polecenie
.BR tar .
.TP
.BR --extract ", " -x ", " \-\-vextract ", " -X
Rozpakowuje zawarto¶æ archiwum do podanego
.IR katalogu .

.BR \-\-vextract " (" -X ")"
wy¶wietla nazwy plików, które s± rozpakowywane, za¶
.BR \-\-extract " (" -x ")"
rozpakowuje pliki bez podawania ¿adnych komunikatów, prócz komunikatów b³êdów.

Proszê zauwa¿yæ, ¿e rozpakowanie pakietu w katalogu g³ównym
.I nie
jest odpowiednikiem zainstalowania pakietu! Do tego celu s³u¿y
wy³±cznie polecenie
.BR dpkg .

Je¶li wskazany
.I katalog
nie istnieje, zostanie utworzony.
.TP
.BR --fsys-tarfile
Rozpakowuje pliki z archiwum i wysy³a je na standardowe wyj¶cie w postaci
formatu polecenia
.BR tar .
Gdy ta operacja zostanie po³±czona z 
.BR tar 'em,
mo¿liwe jest rozpakowanie tylko wybranych plików z archiwum.
.TP
.BR --control ", " -e
Rozpakowuje pliki kontrolne pakietu do podanego 
.IR katalogu .

Je¶li
.IR katalog
nie zosta³ okre¶lony, pliki s± rozpakowywane do podkatalogu
.B DEBIAN
w katalogu bie¿±cym.

W razie potrzeby, katalog docelowy bêdzie utworzony.
.TP
.BR --help ", " -h
Wy¶wietla informacje o sposobie u¿ycia
.BR dpkg\-deb ,
podaj±c zestawienie jego opcji.
.TP
.BR --version
Wy¶wietla informacje o numerze wersji
.BR dpkg\-deb .
.TP
.BR --licence
Wy¶wietla informacje o licencji
.B dpkg\-deb 
oraz braku jego gwarancji. (Obs³ugiwany jest tak¿e amerykañski sposób
pisowni
.BR \-\-license .)
.SH INNE OPCJE
.TP
.BR --new
Upewnia siê, ¿e 
.B dpkg\-deb
utworzy ,,nowy'' format archiwum. Ta opcja jest domy¶lna.
.TP
.BR --old
Wymusza utworzenie przez
.B dpkg\-deb
,,starego'' formatu archiwum. Ten format jest s³abo obs³ugiwany przez
narzêdzia spoza dystrybucji Debiana i obecnie jest przestarza³y. Ta opcja
jest u¿yteczna jedynie w przypadku korzystania z wersji dpkg wcze¶niejszej
ni¿ 0.93.76 (wrzesieñ 1995), która by³a opublikowana jedynie dla i386 a.out.
.TP
.BR --nocheck
Powoduje, ¿e polecenie
.B "dpkg\-deb \-\-build" 
nie bêdzie sprawdzaæ zawarto¶ci archiwum. W ten sposób mo¿na utworzyæ
niepoprawny pakiet, je¶li zajdzie taka potrzeba.
.TP
.BR --debug ", " -D
W³±cza opcjê debuggera. Nie jest to zbyt interesuj±ce.
.SH B£ÊDY
.B dpkg-deb -I 
.IB package1 .deb
.IB package2 .deb
dzia³a niepoprawnie.

Brak sprawdzania autentyczno¶ci plików
.BR .deb .
Tak naprawdê, to nawet nie jest sprawdzana suma kontrolna archiwum.

Nie nale¿y u¿ywaæ
.B dpkg\-deb
do instalowania oprogramowania! Do tego celu nale¿y skorzystaæ z
.BR dpkg ,
który zainstaluje poprawnie pliki i uruchomi potrzebne skrypty
instalacyjne.
.SH ZOBACZ TAK¯E
.BR deb (5),
.BR deb-control (5),
.BR dpkg (8),
.BR dselect (8).
.SH AUTOR
.B dpkg\-deb
i ten podrêcznik napisa³ Ian Jackson ((C)1995-1996),
udostêpnione na Ogólnej Licencji Publicznej GNU; BRAK JAKIEJKOLWIEK GWARANCJI.
Szczegó³y zobacz w
.B /usr/share/doc/dpkg/copyright
oraz
.BR /usr/share/common-licences/GPL .
