.\" {PTM/WK/2000-V}
.ds VE LPRng-3.6.12
.TH LPRACCNT 1 \*(VE "LPRng"
.ig
lpraccnt.1,v 3.39 1998/03/29 18:37:49 papowell Exp
..
.SH NAZWA
lpraccnt \- otrzymaj informacjê rozliczeniow± drukowania
.SH SK£ADNIA
.B lpraccnt
.RB [ \-p
.IR port ]
.RB [ \-D
.IR debuglevel ]
.SH OPIS
.PP
Program
.B lpraccnt
jest szablonem programu rozliczania kosztów drukarki.
Otwiera zadany port TCP, a nastêpnie oczekuje na przes³anie informacji
rozliczeniowej lub innej.
Wypisuje tê informacjê na standardowym wyj¶ciu.
.SH OPCJE
.IP "\fB\-p \fIport\fR" 5
czeka na po³±czenia na tym porcie (domy¶lnie 3000).
.IP "\fB\-D \fIdebuglevel\fR" 5
ustawia poziom informacji diagnostycznych na wskazan± warto¶æ.
.SH "ZOBACZ TAK¯E"
.BR lpd.conf (5),
.BR lpc (8),
.BR lpd (8),
.BR lpr (1),
.BR lpq (1),
.BR lprm (1),
.BR printcap (5),
.BR lpd.perms (5),
.BR pr (1).
.SH "HISTORIA"
LPRng jest rozszerzonym systemem buforowania wydruku o funkcjonalno¶ci podobnej
do oprogramowania Berkeley LPR. List± dyskusyjn± o LPRng jest lprng@lprng.com;
subskrypcja przez wys³anie listu do lprng-request@lprng.com ze s³owem
`subscribe` w tre¶ci.
Oprogramowanie to jest dostêpne z ftp://ftp.astart.com/pub/LPRng.
.SH "AUTOR"
Patrick Powell <papowell@astart.com>.
