.\" {PTM/WK/1999-XII}
.\" Translation update: Robert Luberda <robert@debian.org>, May 2003, man-db 2.4.1
.\" $Id: manpath.1,v 1.3 2003/05/29 10:59:27 robert Exp $
.\"
.\" Man page for manpath
.\"
.\" Copyright (C), 1995, Graeme W. Wilford. (Wilf.)
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the COPYING file that comes with the
.\" man-db distribution.
.\"
.\" Sun Jan 22 22:15:17 GMT 1995 Wilf. (G.Wilford@ee.surrey.ac.uk)
.\"
.TH manpath 1 "7 wrze¶nia 2001" "2.4.1" "Narzêdzia przegl±darki stron man"
.SH NAZWA
manpath \- okre¶la ¶cie¿kê przeszukiwania dla stron podrêcznika man
.SH SK£ADNIA
.B manpath
.B manpath
.RB [\| \-qgdc \|]
.RB [\| \-m
.IR system \|[\|,.\|.\|.\|]\|]
.SH OPIS
Je¿eli ustawiona jest zmienna
.RB $ MANPATH ,
to
.B manpath
po prostu wy¶wietli jej zawarto¶æ i wy¶le ostrze¿enie.
Je¶li nie, to
.B manpath
okre¶li odpowiedni± hierarchiê ¶cie¿ek poszukiwania stron podrêcznika man
i wy¶wietli wyniki.

¦cie¿ka poszukiwañ, w postaci listy rozdzielonych dwukropkami katalogów,
okre¶lana jest przy pomocy informacji pozyskanej z pliku konfiguracyjnego
man-db -
.RI ( "/etc/man_db.config" )
oraz ¶rodowiska u¿ytkowników.
.SH OPCJE
.TP
.B \-q, \-\-quiet
Nie wysy³a ostrze¿eñ.
.TP
.B \-d, \-\-debug
Tworzy informacjê diagnostyczn± (debug).
.TP
.B \-c, \-\-catpath
Tworzy ¶cie¿kê catpath [do stron w postaci catman] zamiast manpath.
Po ustaleniu ¶cie¿ki manpath, ka¿dy jej element zamieniany jest na jego
odpowiednik catpath.
.TP
.B \-g, \-\-global
Twórz ¶cie¿kê manpath sk³adaj±c± siê ze wszystkich ¶cie¿ek wymienionych
jako 'globalne' w pliku konfiguracyjnym man-db.
.\"
.\" Due to the rather silly limit of 6 args per request in some `native'
.\" *roff compilers, we have do the following to get the two-line
.\" hanging tag on one line. .PP to begin a new paragraph, then the
.\" tag, then .RS (start relative indent), the text, finally .RE
.\" (end relative indent).
.\"
.PP
.B \-m
.I system\c
.RB \|[\|,.\|.\|.\|]\| ,
.BI \-\-systems= system\c
\|[\|,.\|.\|.\|]
.RS
Je¶li ten system ma dostêp do hierarchii stron man innego systemu
operacyjnego, to mo¿na wykorzystaæ tê opcjê do w³±czenia tych hierarchii
do wyniku dzia³ania
.BR manpath .
W celu w³±czenia hierarchii stron podrêcznika man z systemu NewOS u¿yj opcji
.B \-m
.BR NewOS .

Podany
.I system
mo¿e byæ kombinacj± oddzielonych przecinkami nazw systemów operacyjnych.
Je¿eli chcemy w³±czyæ hierarchie stron man macierzystego systemu
operacyjnego, to musimy u¿yæ
.B man
jako nazwy systemu w ³añcuchu argumentów.
Niniejsza opcja uniewa¿nia ewentualne u¿ycie zmiennej ¶rodowiska
.RB $ SYSTEM .
.RE
.TP
.B \-h, \-\-help
Wy¶wietla informacjê pomocy i koñczy pracê.
.TP
.B \-V, \-\-version
Wy¶wietla informacjê o wersji i autorze.
.SH ¦RODOWISKO
.TP
.B MANPATH
Je¿eli ustawiona jest zmienna
.RB $ MANPATH ,
to
.B manpath
wy¶wietli jej warto¶æ zamiast okre¶lenia jej na bie¿±co.
Je¿eli zmienna
.RB $ MANPATH
zaczyna siê od dwukropka, to warto¶æ tej zmiennej jest dodawana do listy
pozyskanej z plików konfiguracyjnych.
Je¿eli dwukropek umieszczono na koñcu warto¶ci tej zmiennej, to ta
pozyskana lista ¶cie¿ek jest dodawana na koniec zmiennej.
Je¿eli warto¶æ tej zmiennej zawiera podwójny dwukropek
.RB ( :: ),
to pozyskana lista ¶cie¿ek jest wstawiana do  ¶rodka warto¶ci zmiennej, pomiêdzy
dwukropki.
.TP
.B SYSTEM
Je¿eli ustawiona jest zmienna
.RB $ SYSTEM ,
to ma to taki sam skutek, jak przekazanie jej warto¶ci jako argumentu opcji
.BR \-m .
.SH PLIKI
.TP \w'/etc/man_db.config'u+2n
.I /etc/man_db.config
Systemowy plik konfiguracyjny.
.SH "ZOBACZ TAK¯E"
.BR apropos (1),
.BR whatis (1),
.BR man (1).
.SH AUTOR
.nf
Wilf. (G.Wilford@ee.surrey.ac.uk).
Fabrizio Polacco (fpolacco@debian.org).
.fi
