.\" {PTM/WK/0.1/15-07-1999/"wy¶wietla miejsce zajmowane przez katalog DOS"}
.TH mdu 1 "15 lipca 1999" mtools-3.9.6
.SH NAZWA
mdu - wy¶wietla ilo¶æ miejsca zajmowanego przez katalog DOS
.SH SK£ADNIA
.BR mdu " [" \-as ]
.RI [ plikiDOS ...]
.SH OPIS
\fBmdu\fR podaje obszar zajmowany przez katalog, jego podkatalogi i pliki.
Podobne jest do unixowego polecenia \fBdu\fR. Rozmiar klastra mo¿na ustaliæ
przy pomocy polecenia \fBminfo\fR.
.SH OPCJE
.TP
.B \-a
Wszystkie pliki. Poka¿ równie¿ obszar zajmowany przez pojedyncze pliki.
.TP
.B \-s 
Poka¿ tylko obszar ca³kowity, nie wy¶wietlaj szczegó³ów dla ka¿dego
podkatalogu.
.RE
.SH UWAGI
Niniejsza, polska wersja dokumentacji, powsta³a jako t³umaczenie pliku
Texinfo pakietu mtools wersji 3.9.6. W stosunku do automatycznie generowanej
z Textinfo dokumentacji oryginalnej dokonano przesuniêcia sekcji opisuj±cej
konwersjê dokumentacji do \fBmtools\fR(1). Tam te¿ znajdziesz notê prawn±
dotycz±c± rozpowszechniania, modyfikacji i t³umaczenia dokumentacji pakietu
mtools
