.\" {PTM/WK/0.1/15-07-1999/"sprawdza i wy¶wietla konfiguracjê mtools"}
.TH mtoolstest 1 "15 lipca 1999" mtools-3.9.6
.SH NAZWA
mtoolstest - sprawdza i wy¶wietla konfiguracjê mtools
.SH OPIS
Polecenie \fBmtoolstest\fR sprawdza pliki konfiguracyjne pakietu
\fBmtools\fR. Nie posiada ¿adnych argumentów. Odczytuje pliki konfiguracyjne
\fBmtools\fR i wysy³a ca³o¶æ konfiguracji na standardowe wyj¶cie. Uzyskany
wynik mo¿e byæ z kolei u¿yty jako nowy plik konfiguracyjny (chocia¿ mo¿e byæ
po¿±dane usuniêcie powtarzaj±cych siê linii). Jest przydatny do konwersji
plików konfiguracyjnych starej postaci na now± postaæ.
.SH UWAGI
Niniejsza, polska wersja dokumentacji, powsta³a jako t³umaczenie pliku
Texinfo pakietu mtools wersji 3.9.6. W stosunku do automatycznie generowanej
z Textinfo dokumentacji oryginalnej dokonano przesuniêcia sekcji opisuj±cej
konwersjê dokumentacji do \fBmtools\fR(1). Tam te¿ znajdziesz notê prawn±
dotycz±c± rozpowszechniania, modyfikacji i t³umaczenia dokumentacji pakietu
mtools
