.\" {PTM/PB/0.1/02-10-1998/"Powiedz, jak długo system pracuje"}
.\" Translation 1998 Przemek Borys <pborys@dione.ids.pl>
.\"             -*-Nroff-*-
.\"
.TH UPTIME 1 "26 Jan 1993" "Cohesive Systems" "Podręcznik programisty linuksowego"
.SH NAZWA
uptime \- Powiedz jak długo system jest włączony.
.SH SKŁADNIA
.B uptime
.br
.BR uptime " [" "\-V" ]
.SH OPIS
\fI Uwaga! To tłumaczenie może być nieaktualne!\fP
.PP
.B uptime
wyświetla w jednej linijce następujące dane.
Bieżący czas,
jak długo system jest włączony,
jak wielu użytkowników jest obecnie zalogowanych,
load average (obciążenie) z ostatnich 1, 5 i 15 minut.
.sp
Są to te same dane, które można uzyskać w nagłówkowej linii wyświetlanej
przez
.BR w (1).
.SH PLIKI
.IR /var/run/utmp "	dane o tym, kto obecnie jest zalogowany"
.br
.IR /proc "	informacje o procesach"
.SH AUTORZY
.B uptime
został napisany przez Larry'ego Greenfielda (greenfie@gauss.rutgers.edu) i
Michaela K. Johnsona (johnsonm@sunsite.unc.edu).
.SH "ZOBACZ TAKŻE"
.BR ps (1),
.BR top (1),
.BR utmp (5),
.BR w (1)
.SH "INFORMACJE O TŁUMACZENIU"
Powyższe tłumaczenie pochodzi z nieistniejącego już Projektu Tłumaczenia Manuali i 
\fImoże nie być aktualne\fR. W razie zauważenia różnic między powyższym opisem
a rzeczywistym zachowaniem opisywanego programu lub funkcji, prosimy o zapoznanie 
się z oryginalną (angielską) wersją strony podręcznika za pomocą polecenia:
.IP
man \-\-locale=C 1 uptime
.PP
Prosimy o pomoc w aktualizacji stron man \- więcej informacji można znaleźć pod
adresem http://sourceforge.net/projects/manpages\-pl/.
