.\"  {PTM/GSN/0.5/23-02-1999/"wypisz liczbê bajtów, s³ów i linii w plikach"}
.\" poszerzenie i aktualizacja do GNU textutils 2.0 PTM/WK/2000-IV
.ig
Transl.note: based on GNU man page wc.1 and textutils.info
 
Copyright 1994, 95, 96, 1999 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be stated in a
translation approved by the Foundation.
..
.TH WC "1" FSF "sierpieñ 1999" "Narzêdzia tekstowe GNU 2.0"
.SH NAZWA
wc \- wypisz liczbê bajtów, s³ów i linii w plikach
.SH SK£ADNIA
.TP 4
.B wc
.RB [ \-clwL ]
.RB [ \-\-bytes ]
.RB [ \-\-chars ]
.RB [ \-\-lines ]
.RB [ \-\-words ]
.br
.RB [ \-\-max\-line\-length ]
.RB [ \-\-help ]
.RB [ \-\-version ]
.RI [ plik ...]
.SH OPIS
Dokumentacja niniejsza nie jest ju¿ utrzymywana i mo¿e byæ niedok³adna
lub niekompletna.  Autorytatywnym ¼ród³em jest obecnie dokumentacja
Texinfo.  Dostêp do niej uzyskasz wpisuj±c w wierszu poleceñ:
.RS
.B pinfo wc
.RE
lub
.RS
.BR "info wc" .
.RE
.PP
Ta strona podrêcznika opisuje polecenie \fBwc\fP w wersji GNU.
.PP
.B wc
(word count)
liczy liczbê bajtów, s³ów oddzielonych bia³ymi znakami, oraz znaków koñca
linii w ka¿dym podanym pliku lub w standardowym wej¶ciu (je¶li nie
podano ¿adnego pliku albo podano plik zwany '\-').  Wypisuje jedn±
liniê danych o liczbach dla ka¿dego pliku, a je¶li plik ów zosta³ podany jako
argument, po liczbie(ach) wypisuje nazwê pliku.  Je¶li podano wiêcej
ni¿ jedn± nazwê pliku,
.B wc
wypisuje liniê koñcow± zawieraj±c± ³±czne liczby, z nazw± pliku 'total'.
Liczby s± wypisywane w kolejno¶ci: linie, s³owa, bajty.
.PP
Domy¶lnie ka¿da z liczb wypisywana jest w wyrównanym do prawej 7-bajtowym polu,
z jedn± spacj± miêdzy polami. Wówczas liczby i nazwy plików ³adnie wyrównuj± siê
w kolumnach. Jednak POSIX wymaga, by kolumny by³y rozdzielone dok³adnie jedn±
spacj±. Mo¿na wymusiæ na \fBwc\fP przestrzeganie formatu wyj¶cia zgodnego
z POSIX ustawiaj±c zmienn± ¶rodowiska \fBPOSIXLY_CORRECT\fP.
.PP
Domy¶lnie
.B wc
wypisuje wszystkie trzy liczby. Opcjami mo¿na okre¶liæ wypisywanie
tylko niektórych liczb. Kolejne opcje nie uniewa¿niaj± innych, poprzednich,
tak wiêc
.RS
.B wc " \-\-bytes \-\-words"
.RE
wypisze liczbê bajtów oraz liczbê s³ów.
.PP
Z opcj± \fB--max-line-length\fP wypisuje d³ugo¶æ najd³u¿szej linii w ka¿dym
z plików, a je¿eli podano wiêcej ni¿ jeden plik, to równie¿ najwiêksz±
(nie sumê) z tych d³ugo¶ci.
.SH OPCJE
.TP
.BR \-c ", " \-\-bytes ", " \-\-chars
Wypisuje tylko liczbê bajtów.
.TP
.BR \-w ", " \-\-words
Wypisuje tylko liczbê s³ów.
.TP
.BR \-l ", " \-\-lines
Wypisuje tylko liczbê znaków nowej linii.
.TP
.BR \-L ", " \-\-max\-line\-length
Wypisuje tylko d³ugo¶æ najd³u¿szej linii.
.TP
.B "\-\-help"
Wy¶wietla informacjê o stosowaniu programu i dostêpnych opcjach, koñczy pracê.
.TP
.B "\-\-version"
Wy¶wietla numer wersji programu i koñczy pracê.
.SH "ZG£ASZANIE B£ÊDÓW"
B³êdy proszê zg³aszaæ, w jêz. ang., do <bug-textutils@gnu.org>.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH ZOBACZ TAK¯E
.BR sum (1),
.BR cksum (1),
.BR md5sum (1),
.BR textutils (1).
.SH OD T£UMACZA
Zaktualizowano i poszerzono wg dokumentacji Texinfo dla narzêdzi tekstowych
GNU wersji 2.0.
