.\" {PTM/LK/0.1/28-09-1998/"xbmtopbm - konwersja bitmapy X10/X11 do .pbm"}
.\" Tłumaczenie: 28-09-1998 Łukasz Kowalczyk (lukow@tempac.okwf.fuw.edu.pl)
.TH xbmtopbm 1 "31 sierpnia 1988"
.IX xbmtopbm
.SH NAZWA
xbmtopbm \- utwórz przenośną bitmapę (.pbm) z bitmapy typu X10 lub X11 
.SH SKŁADNIA
.B xbmtopbm
.RI [ plik_bitmapa ]
.SH OPIS
\fI Uwaga! To tłumaczenie może być nieaktualne!\fP
.PP
Odczytuje bitmapę typu X10 lub X11. Następnie zapisuje na standardowe
wyjście przenośną bitmapę (.pbm).
.IX "X bitmap"
.IX "X window system"
.SH "ZOBACZ TAKŻE"
pbmtoxbm(1), pbmtox10bm(1), pbm(5)
.SH AUTOR
Copyright (C) 1988 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
.SH "INFORMACJE O TŁUMACZENIU"
Powyższe tłumaczenie pochodzi z nieistniejącego już Projektu Tłumaczenia Manuali i 
\fImoże nie być aktualne\fR. W razie zauważenia różnic między powyższym opisem
a rzeczywistym zachowaniem opisywanego programu lub funkcji, prosimy o zapoznanie 
się z oryginalną (angielską) wersją strony podręcznika za pomocą polecenia:
.IP
man \-\-locale=C 1 xbmtopbm
.PP
Prosimy o pomoc w aktualizacji stron man \- więcej informacji można znaleźć pod
adresem http://sourceforge.net/projects/manpages\-pl/.
