.\" {PTM/LK/0.1/27-09-1998/"ybmtopbm - konwersja pliku 'face' to przeno¶nej bitmapy "}
.\" T³umaczenie: 27-09-1998 £ukasz Kowalczyk (lukow@tempac.okwf.fuw.edu.pl)
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation. This software is provided "as is" without express or
.\" implied warranty.
.TH ybmtopbm 1 "06 marca 1990"
.IX ybmtopbm
.SH NAZWA
ybmtopbm \- utwórz przeno¶n± bitmapê (pbm) z pliku typu "face"
.SH SK£ADNIA
.B ybmtopbm
.RI [ plik_face ]
.SH OPIS
Odczytuje plik w formacie rozpoznawalnym przez programy
.I face
i
.I xbm
napisane przez Benneta Yee (bsy+@cs.cmu.edu).
.\" .IX face
Nastêpnie zapisuje na standardowe wyj¶cie przeno¶n± bitmapê (plik .pbm).
.SH "ZOBACZ TAK¯E"
pbmtoybm(1), pbm(5), face(1), face(5), xbm(1)
.SH AUTOR
Copyright (C) 1991 by Jamie Zawinski and Jef Poskanzer.
