.\" {PTM/WK/1999-10-20}
.\" -*- nroff -*-
.\"
.\" copyright (C) 1997 Stephen Williams <steve@icarus.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH skel 9 "$Date: 1999/10/20 09:41:12 $" "Linux DDI" "Funkcje j±dra"
.\"
.\" Dla pierwszych sekcji wy³±cz przenoszenie wyrazów i wyrównywanie w prawo.
.hlm 0
.na
.\" Aby dzia³a³o apropos nazwa powinna byæ sformatowana w ten sposób
.SH NAZWA
skel \- wzorzec strony podrêcznika dla pozycji w sekcji 9
.\"
.\"
.SH SK£ADNIA
.B #include <linux/linux.h>
.HP
.\"
.\" W³±cz powtórnie przenoszenie wyrazów i wyrównywanie.
.hlm 1
.ad
.SH OPIS
Opisz funkcjê i jej parametry. Sekcja ta nie powinna byæ traktowana jako
wprowadzenie do programowania j±dra, ale jako podrêczny opis funkcji.
Mo¿na przyj±æ za³o¿enie o pewnej podstawowej wiedzy o programowaniu sterowników.
.SH WARTO¦Æ ZWRACANA
Opisz zwracane warto¶ci. Wylicz wszystkie ró¿ni±ce siê warto¶ci i ich zakresy.
.SH DOSTÊPNO¦Æ
Wska¿ wersje j±dra. Je¶li funkcja jest ograniczona do pewnych architektur,
napisz to.
.SH ZOBACZ TAK¯E
.hlm 0
.na
.BR man "(1), " man "(7), " intro "(9)"
.ad
.hlm 1
.PP
Wska¿ te¿ pliki ¼ród³owe j±dra, które implementuj± opisywan± funkcjê.
.SH AUTOR
Kim jeste¶?
.SH B£ÊDY
Opisz wszelkie nietypowe zachowania czy niespodzianki, do których mo¿e
prowadziæ pos³ugiwanie siê funkcj±. Nie mog± to byæ b³êdy, ale po prostu
pechowe efekty uboczne.
